r"""
Generates 300 questions across 6 categories for Chapter 02 (The Jackal and the Dhol) — Book 3
"""
import os, sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CH_DIR = os.path.join(BASE_DIR, "question_bank", "chapter_02")
os.makedirs(CH_DIR, exist_ok=True)

CH_ID = "BK03_CH02"
CH_TITLE = "The Jackal and the Dhol"

# ── 1. MCQs (50) ──
mcqs = [
    ("What kind of tale is 'The Jackal and the Dhol'?", "(A) A Panchatantra Tale", "(B) A Greek Myth", "(C) A Science Fiction Story", "(D) A Historical Essay", "(A)", "It is a Panchatantra Tale.", "Easy", "Remembering", "Genre"),
    ("Why did the king hold a grand party?", "(A) To celebrate his massive victory in battle", "(B) To announce a new law", "(C) To welcome a foreign king", "(D) To celebrate his birthday", "(A)", "He celebrated his massive victory.", "Easy", "Remembering", "Event"),
    ("How did the king fight the battle?", "(A) Valiantly and tirelessly", "(B) Fearfully and slowly", "(C) Lazily and carelessly", "(D) Angrily and recklessly", "(A)", "He fought valiantly and tirelessly.", "Easy", "Remembering", "Battle"),
    ("What kind of enemy did the king fight against?", "(A) A formidable enemy", "(B) A tiny insect", "(C) A friendly neighbour", "(D) A river flood", "(A)", "A formidable enemy.", "Easy", "Remembering", "Enemy"),
    ("What performers were called to the celebration?", "(A) Dancers, singers, and musicians", "(B) Only painters", "(C) Only cooks", "(D) Only soldiers", "(A)", "Dancers, singers, and musicians.", "Easy", "Remembering", "Celebration"),
    ("What happened to the dhol during the celebration?", "(A) It fell and rolled into the nearby forest", "(B) It was stolen by a thief", "(C) It broke into pieces", "(D) It flew into the sky", "(A)", "It fell and rolled into the nearby forest.", "Easy", "Remembering", "Dhol Event"),
    ("Where did the dhol get stuck in the forest?", "(A) In a tree where branches would hit it", "(B) Under a large rock", "(C) Inside a river", "(D) On top of a mountain", "(A)", "Stuck in a tree where branches hit it.", "Easy", "Remembering", "Location"),
    ("Why did the dhol make sounds in the forest?", "(A) Because tree branches were hitting it", "(B) Because an animal was playing it", "(C) Because of magic", "(D) Because the wind was singing", "(A)", "Branches were hitting the dhol.", "Easy", "Remembering", "Sound Cause"),
    ("Who heard the sound of the dhol in the forest?", "(A) A jackal", "(B) A tiger", "(C) A monkey", "(D) An elephant", "(A)", "A jackal heard the sound.", "Easy", "Remembering", "Character"),
    ("What did the jackal think was inside the dhol?", "(A) A soft and delicious animal", "(B) A bag of gold coins", "(C) A musical instrument", "(D) A dangerous snake", "(A)", "He thought a tasty animal was inside.", "Easy", "Remembering", "Assumption"),
    ("What word describes the sound the dhol made?", "(A) Dham-dham", "(B) Tick-tock", "(C) Buzz-buzz", "(D) Chirp-chirp", "(A)", "The dham-dham sound of the dhol.", "Easy", "Remembering", "Sound"),
    ("Who did the jackal tell about the dhol?", "(A) His friend", "(B) The king", "(C) A deer", "(D) The monkey", "(A)", "He told his friend.", "Easy", "Remembering", "Communication"),
    ("What did the jackal tell his friend was inside the dhol?", "(A) A tasty animal stuck between dried leather", "(B) A treasure chest", "(C) A singing bird", "(D) Magic stones", "(A)", "A tasty animal stuck between dried leather.", "Easy", "Remembering", "Claim"),
    ("When did the jackal and his friend go to the dhol?", "(A) At night", "(B) At dawn", "(C) During afternoon", "(D) During the celebration", "(A)", "They went at night.", "Easy", "Remembering", "Time"),
    ("What did the jackals do to the dhol?", "(A) They tore the leather on both sides", "(B) They carried it home", "(C) They buried it underground", "(D) They threw it into a river", "(A)", "They tore the leather on both sides.", "Easy", "Remembering", "Action"),
    ("What did the jackals find inside the dhol after tearing it?", "(A) Nothing — it was empty inside", "(B) A small cat", "(C) Gold coins", "(D) A baby bird", "(A)", "They found nothing inside.", "Easy", "Remembering", "Discovery"),
    ("How did the jackals feel after finding the dhol empty?", "(A) Disappointed", "(B) Happy", "(C) Excited", "(D) Proud", "(A)", "They became disappointed.", "Easy", "Remembering", "Emotion"),
    ("What is the moral of the story?", "(A) Do not act without detailed information", "(B) Always trust your friends", "(C) Be greedy for food", "(D) Never go into the forest", "(A)", "Do not act without detailed information.", "Easy", "Remembering", "Moral"),
    ("What does the word 'valiantly' mean?", "(A) Bravely", "(B) Slowly", "(C) Quietly", "(D) Fearfully", "(A)", "Valiantly means bravely.", "Easy", "Understanding", "Vocabulary"),
    ("What does the word 'formidable' mean?", "(A) Inspiring fear", "(B) Very small", "(C) Extremely funny", "(D) Very kind", "(A)", "Formidable means inspiring fear.", "Easy", "Understanding", "Vocabulary"),
    ("What does the word 'conclude' mean?", "(A) To form an opinion based on understanding", "(B) To start something new", "(C) To run away quickly", "(D) To eat food", "(A)", "Conclude means to form an opinion based on understanding.", "Easy", "Understanding", "Vocabulary"),
    ("What was the dhol originally used for?", "(A) Entertainment — music at the king's victory celebration", "(B) Cooking food", "(C) Carrying water", "(D) Building houses", "(A)", "Used for music at the celebration.", "Easy", "Understanding", "Purpose"),
    ("Did the jackal observe the dhol carefully before deciding?", "(A) He observed it from a distance but drew a wrong conclusion", "(B) He inspected every part thoroughly", "(C) He asked a wise owl for advice", "(D) He ignored it completely", "(A)", "He observed from a distance but concluded wrongly.", "Easy", "Understanding", "Observation"),
    ("Was the jackal correct in his assumption about the dhol?", "(A) No, the dhol was just an empty drum", "(B) Yes, there was a real animal inside", "(C) Yes, but the animal escaped", "(D) No, it was full of water", "(A)", "No, the dhol was just an empty drum.", "Easy", "Understanding", "Assumption Check"),
    ("What title is given to Chapter 02?", "(A) The Jackal and the Dhol", "(B) The Foolish Pandit", "(C) Two Cats and the Monkey", "(D) Fountain Pen", "(A)", "Chapter 02 is titled 'The Jackal and the Dhol'.", "Easy", "Remembering", "Chapter Title"),
    # Medium (26-40)
    ("Why did the jackal conclude that something delicious was inside the dhol?", "(A) He heard the dham-dham sound and assumed it was a soft creature making the noise", "(B) He could smell food from inside", "(C) He saw an animal go inside the dhol", "(D) His friend told him about the animal", "(A)", "He wrongly associated the drumming sound with a creature.", "Medium", "Analyzing", "Faulty Reasoning"),
    ("What is the connection between the king's party and the jackal's story?", "(A) The dhol fell during the celebration and ended up in the forest where the jackal found it", "(B) The king invited the jackal to the party", "(C) The jackal was a performer at the party", "(D) There is no connection", "(A)", "The dhol from the celebration ended up in the forest.", "Medium", "Understanding", "Plot Connection"),
    ("How does the story show that assumptions without evidence can be dangerous?", "(A) The jackal assumed food was inside based only on sound, wasted great effort, and found nothing", "(B) The jackal found treasure inside", "(C) The king lost his battle because of assumptions", "(D) The monkey stole the dhol", "(A)", "Assumption based only on sound led to wasted effort.", "Medium", "Analyzing", "Theme Analysis"),
    ("What effort did the jackals put into tearing the dhol?", "(A) Great effort — they tore leather on both sides with difficulty", "(B) No effort at all — it opened easily", "(C) They used tools from the village", "(D) They asked the king's soldiers to help", "(A)", "Great effort to tear leather on both sides.", "Medium", "Understanding", "Effort"),
    ("How does the moral 'Do not act without detailed information' apply to real life?", "(A) Before making decisions, gather all facts; otherwise you may waste time and energy on wrong assumptions", "(B) Always act quickly without thinking", "(C) Never ask questions about anything", "(D) Trust your first guess always", "(A)", "Gather facts before decisions to avoid wasted effort.", "Medium", "Applying", "Real-Life Application"),
    ("Why is the jackal called foolish in this story?", "(A) He mistook a non-living drum sound for a living creature and wasted his night's effort", "(B) He was too brave", "(C) He helped the king win the battle", "(D) He could play musical instruments", "(A)", "Mistook a drum sound for a living creature.", "Medium", "Evaluating", "Character Evaluation"),
    ("What literary device is used when the jackal assumes the sound means food?", "(A) Dramatic irony — the reader knows it is a drum but the jackal does not", "(B) Rhyme scheme", "(C) Alliteration", "(D) Metaphor for happiness", "(A)", "Dramatic irony — reader knows, jackal does not.", "Medium", "Analyzing", "Literary Device"),
    ("Compare the jackal's behaviour with Pandit Someshwar's behaviour from Chapter 01.", "(A) Both acted without thinking — Someshwar tested the booti on a lion, the jackal assumed food was inside the dhol", "(B) Both were rewarded for their actions", "(C) Both asked for advice first", "(D) Both were very wise characters", "(A)", "Both acted without thinking about consequences.", "Medium", "Comparing", "Cross-Chapter Comparison"),
    ("What could the jackal have done to verify his assumption before tearing the dhol?", "(A) Looked through holes, smelled for food, or tapped the dhol to understand it was hollow", "(B) Eaten the dhol immediately", "(C) Run away without investigating", "(D) Asked the tree for advice", "(A)", "Look, smell, or tap to verify before acting.", "Medium", "Applying", "Alternative Action"),
    ("How does Panchatantra use animal characters to teach human lessons?", "(A) Animals like the jackal represent human flaws such as greed and hasty judgement", "(B) Animals represent real scientific discoveries", "(C) Animals are used to teach cooking", "(D) Animals symbolise weather patterns", "(A)", "Animals represent human flaws like greed and hasty judgement.", "Medium", "Evaluating", "Storytelling Technique"),
    ("What role does greed play in the jackal's decision-making?", "(A) Greed for food clouded his judgement and prevented careful investigation", "(B) Greed made him share fairly with everyone", "(C) Greed made him build a house", "(D) He was not greedy at all", "(A)", "Greed clouded his judgement.", "Medium", "Analyzing", "Character Flaw"),
    ("Why did the jackals go at night instead of during the day?", "(A) Night provided cover and secrecy for their plan to catch the 'animal'", "(B) Because the forest was closed during the day", "(C) The dhol only made sounds at night", "(D) They were sleeping during the day", "(A)", "Night provided cover and secrecy.", "Medium", "Understanding", "Timing Choice"),
    ("What does 'all their labour got wasted' mean in the context of the story?", "(A) All the hard physical effort of tearing the dhol's leather was for nothing since it was empty", "(B) They lost their jobs", "(C) They ran out of food at home", "(D) They forgot where the dhol was", "(A)", "Hard effort was for nothing since the dhol was empty.", "Medium", "Understanding", "Phrase Interpretation"),
    ("How does the setting of the forest contribute to the jackal's confusion?", "(A) The forest's natural sounds (wind, branches) made the dhol produce deceptive dham-dham sounds", "(B) The forest was full of other jackals who confused him", "(C) The forest had no trees at all", "(D) There was a wizard in the forest", "(A)", "Forest's branches hitting the dhol created deceptive sounds.", "Medium", "Analyzing", "Setting Analysis"),
    ("What feeling would a Class 3 student learn to avoid after reading this story?", "(A) Acting impulsively based on incomplete information or assumptions", "(B) Reading books carefully", "(C) Sharing food with friends", "(D) Listening to music", "(A)", "Avoid acting impulsively on incomplete information.", "Medium", "Evaluating", "Lesson Application"),
    # Hard (41-50)
    ("Analyse the cause-and-effect chain from the king's celebration to the jackal's disappointment.", "(A) Victory → Celebration → Dhol falls → Rolls into forest → Stuck in tree → Branches hit dhol → Sound → Jackal hears → Assumes food → Tears dhol → Finds nothing → Disappointment", "(B) King → Dhol → Jackal → Food → Happy", "(C) Jackal → King → Battle → Celebration", "(D) There is no cause-and-effect", "(A)", "Complete 12-step cause-effect chain.", "Hard", "Analyzing", "Cause-Effect Chain"),
    ("Evaluate the philosophical depth of the moral 'Do not act without detailed information'.", "(A) It teaches epistemic caution — decisions should be based on verified evidence, not assumptions from limited sensory data", "(B) It means never do anything at all", "(C) It teaches that sounds are always dangerous", "(D) It promotes laziness", "(A)", "Epistemic caution — evidence over assumption.", "Hard", "Evaluating", "Philosophical Analysis"),
    ("Compare the jackal's information-gathering failure with modern misinformation problems.", "(A) Just as the jackal relied on one misleading sound, people today often act on unverified social media rumours", "(B) The jackal used advanced technology", "(C) Modern people never make mistakes", "(D) Social media did not exist in Panchatantra times so there is no comparison", "(A)", "Both involve acting on unverified incomplete information.", "Hard", "Evaluating", "Modern Parallel"),
    ("Critique the jackal's reasoning from an evidence-based thinking perspective.", "(A) He committed a confirmation bias — hearing the sound, he imagined food and never tested his hypothesis before acting", "(B) His reasoning was perfectly logical", "(C) He used scientific methods", "(D) He asked other animals for peer review", "(A)", "Confirmation bias — imagined food, never tested hypothesis.", "Hard", "Evaluating", "Critical Thinking"),
    ("Synthesize the core lesson of Chapter 02 in a single principle for young learners.", "(A) Verify before you act — investigate thoroughly, question your assumptions, and gather complete evidence before committing effort", "(B) Always eat whatever you find", "(C) Never go outside at night", "(D) Trust every sound you hear in the forest", "(A)", "Verify before you act.", "Hard", "Synthesizing", "Core Principle"),
    ("How does the dhol function as a symbol in the story?", "(A) The dhol symbolises deceptive appearances — something that seems alive and promising on the outside but is hollow and empty within", "(B) The dhol represents wealth", "(C) The dhol represents the king's power", "(D) The dhol has no symbolic meaning", "(A)", "Deceptive appearances — seems alive but is hollow.", "Hard", "Analyzing", "Symbolism"),
    ("Assess how the story builds scientific inquiry skills in children.", "(A) It teaches hypothesis testing — the jackal had a hypothesis (food inside) but failed to test it before investing effort", "(B) It teaches memorisation", "(C) It has nothing to do with science", "(D) It teaches multiplication tables", "(A)", "Teaches hypothesis testing.", "Hard", "Evaluating", "Scientific Method"),
    ("Why is the Panchatantra still relevant after thousands of years?", "(A) Its morals about human behaviour (greed, haste, poor judgement) are timeless and apply across all eras", "(B) Because it uses modern language", "(C) Because it only discusses technology", "(D) It is no longer relevant", "(A)", "Timeless morals about human behaviour.", "Hard", "Evaluating", "Relevance"),
    ("Formulate a classroom discussion question based on the jackal's mistake.", "(A) 'Have you ever assumed something was true without checking, and what happened?' — encourages reflective thinking", "(B) 'What is the colour of a dhol?'", "(C) 'How many legs does a jackal have?'", "(D) 'What year was Panchatantra written?'", "(A)", "Reflective thinking discussion question.", "Hard", "Creating", "Pedagogical Design"),
    ("Synthesize how Chapters 01 and 02 together build a framework of cautious decision-making.", "(A) Ch 01 warns against acting without thinking about consequences; Ch 02 warns against acting without gathering information — together they teach: Think + Investigate before acting", "(B) Both chapters are about cooking food", "(C) Neither chapter has a moral lesson", "(D) They teach opposite lessons that contradict each other", "(A)", "Think (Ch01) + Investigate (Ch02) before acting.", "Hard", "Synthesizing", "Cross-Chapter Synthesis"),
]

mcq_content = f"# MCQs — Chapter 02: {CH_TITLE}\n\n> **Category**: Multiple Choice Questions | **Total**: 50 Questions | **Marks**: 1 each\n\n---\n\n"
for idx, (q, a, b, c, d, ans, exp, diff, bloom, topic) in enumerate(mcqs, 1):
    mcq_content += f"### Question {idx}\n- **Question ID**: {CH_ID}_MCQ_{idx:03d}\n- **Difficulty**: {diff}\n- **Bloom Level**: {bloom}\n- **Topic**: {topic}\n- **Marks**: 1\n\n**Question**: {q}\n\n- {a}\n- {b}\n- {c}\n- {d}\n\n- **Answer Key**: **{ans}** — {exp}\n\n---\n\n"
with open(os.path.join(CH_DIR, "mcqs.md"), "w", encoding="utf-8") as f: f.write(mcq_content)

# ── 2. Fill in the Blanks (50) ──
fibs = [
    ("Once upon a time, a king fought a long battle _______ and tirelessly.", "valiantly", "Easy"),
    ("The king won the battle against a _______ enemy.", "formidable", "Easy"),
    ("To celebrate his victory, the king decided to hold a grand _______.", "party", "Easy"),
    ("Many performers were called for dancing, singing, and _______.", "music", "Easy"),
    ("During the celebration, one _______ fell and rolled into the forest.", "dhol", "Easy"),
    ("The dhol got stuck in a _______ in the forest.", "tree", "Easy"),
    ("The tree branches would hit the dhol and make _______.", "sounds", "Easy"),
    ("A _______ passed through the forest and heard the dhol's sound.", "jackal", "Easy"),
    ("The jackal heard the _______ sound coming from the dhol.", "dham-dham", "Easy"),
    ("The jackal thought the sound was made by a soft and _______ animal.", "delicious", "Easy"),
    ("The jackal decided the sound was not from a _______ animal.", "harmful", "Easy"),
    ("The jackal observed the dhol from a _______ for some time.", "distance", "Easy"),
    ("The jackal went back to tell his _______ about the dhol.", "friend", "Easy"),
    ("The jackal said a tasty animal was stuck between the dried _______ of the dhol.", "leather", "Easy"),
    ("At _______, the jackals went to catch the animal inside the dhol.", "night", "Easy"),
    ("They started tearing the _______ on both sides with great effort.", "leather", "Easy"),
    ("After tearing the leather, they found _______ inside the dhol.", "nothing", "Easy"),
    ("The jackals became _______ after realising their labour was wasted.", "disappointed", "Easy"),
    ("The moral of the story is: Do not act without detailed _______.", "information", "Easy"),
    ("Valiantly means _______.", "bravely", "Easy"),
    ("Formidable means inspiring _______.", "fear", "Easy"),
    ("Conclude means to form an _______ based on understanding.", "opinion", "Easy"),
    ("The dhol rolled from one place to _______ in the forest.", "another", "Easy"),
    ("The king's celebration included _______, singing, and music.", "dancing", "Easy"),
    ("The jackals' hard _______ was completely wasted.", "labour", "Easy"),
    ("The jackal's wrong _______ about food inside the dhol led to wasted effort.", "assumption", "Medium"),
    ("The dhol produced sounds because of natural _______ forces, not a living creature.", "external", "Medium"),
    ("The jackal committed a reasoning error by confusing sound with _______.", "food", "Medium"),
    ("Acting without complete _______ leads to disappointment.", "information", "Medium"),
    ("The jackal's greed for food clouded his _______.", "judgement", "Medium"),
    ("Both jackals put great physical _______ into tearing the drum.", "effort", "Medium"),
    ("The dhol was originally a musical _______ used at the king's party.", "instrument", "Medium"),
    ("The jackals should have _______ their assumption before acting.", "verified", "Medium"),
    ("Panchatantra tales use animal characters to teach moral _______.", "lessons", "Medium"),
    ("The empty dhol symbolises deceptive _______ that mislead observers.", "appearances", "Medium"),
    ("Night-time secrecy did not help the jackals avoid _______.", "disappointment", "Medium"),
    ("The forest setting created natural _______ that deceived the jackal.", "sounds", "Medium"),
    ("Evidence-based thinking requires testing a _______ before committing effort.", "hypothesis", "Medium"),
    ("Hasty conclusions without investigation result in wasted _______.", "effort", "Medium"),
    ("The jackal's story parallels modern problems of acting on unverified _______.", "rumours", "Medium"),
    ("The jackal failed to apply _______ inquiry before drawing conclusions.", "scientific", "Hard"),
    ("Confirmation _______ made the jackal see only what he wanted to believe.", "bias", "Hard"),
    ("The dhol as a literary symbol represents hollow _______ without substance.", "promises", "Hard"),
    ("Epistemic _______ demands verifying evidence before drawing conclusions.", "caution", "Hard"),
    ("The moral encourages developing critical _______ skills from childhood.", "thinking", "Hard"),
    ("Chapters 01 and 02 together build a framework of cautious _______.", "decision-making", "Hard"),
    ("The jackal's sensory _______ of sound led to an incorrect cognitive conclusion.", "perception", "Hard"),
    ("Greed combined with insufficient _______ produces regrettable outcomes.", "evidence", "Hard"),
    ("The Panchatantra's _______ relevance proves human nature remains consistent.", "timeless", "Hard"),
    ("Chapter 02 develops reading comprehension through vocabulary, inference, and moral _______.", "reasoning", "Hard"),
]
fib_content = f"# Fill in the Blanks — Chapter 02: {CH_TITLE}\n\n> **Category**: Fill in the Blanks | **Total**: 50 Questions | **Marks**: 1 each\n\n---\n\n"
for idx, (sent, ans, diff) in enumerate(fibs, 1):
    fib_content += f"### Question {idx}\n- **Question ID**: {CH_ID}_FIB_{idx:03d}\n- **Difficulty**: {diff}\n- **Marks**: 1\n\n**Question**: {sent}\n\n- **Answer Key**: **{ans}**\n\n---\n\n"
with open(os.path.join(CH_DIR, "fill_in_the_blanks.md"), "w", encoding="utf-8") as f: f.write(fib_content)

# ── 3. True/False (50) ──
tfs = [
    ("A king fought a long battle valiantly and won.", "True", "Easy"),
    ("The king held a grand party to celebrate his defeat.", "False", "Easy"),
    ("Many performers were called for dancing, singing, and music.", "True", "Easy"),
    ("During the celebration, a dhol fell and rolled into the forest.", "True", "Easy"),
    ("The dhol got stuck in a river in the forest.", "False", "Easy"),
    ("Tree branches hitting the dhol caused it to make sounds.", "True", "Easy"),
    ("A tiger heard the sound of the dhol.", "False", "Easy"),
    ("The jackal thought a delicious animal was inside the dhol.", "True", "Easy"),
    ("The jackal immediately ran away in fear after hearing the sound.", "False", "Easy"),
    ("The jackal told his friend about the dhol.", "True", "Easy"),
    ("The jackals went to the dhol during the daytime.", "False", "Easy"),
    ("The jackals tore the leather of the dhol on both sides.", "True", "Easy"),
    ("The jackals found a small cat inside the dhol.", "False", "Easy"),
    ("The jackals were disappointed after finding the dhol empty.", "True", "Easy"),
    ("The moral of the story is 'Do not act without detailed information'.", "True", "Easy"),
    ("'Valiantly' means in a cowardly way.", "False", "Easy"),
    ("'Formidable' means inspiring fear.", "True", "Easy"),
    ("'Conclude' means to start something new.", "False", "Easy"),
    ("The dhol was originally used as a musical instrument.", "True", "Easy"),
    ("The jackal observed the dhol from close range before deciding.", "False", "Easy"),
    ("The sound of the dhol was 'dham-dham'.", "True", "Easy"),
    ("The jackal thought the dhol contained gold coins.", "False", "Easy"),
    ("The king fought against a formidable enemy.", "True", "Easy"),
    ("The jackal and his friend succeeded in finding food inside.", "False", "Easy"),
    ("Chapter 02 is titled 'The Jackal and the Dhol'.", "True", "Easy"),
    ("The jackal's assumption was based entirely on sound, not visual evidence.", "True", "Medium"),
    ("The jackal verified his assumption before tearing the dhol.", "False", "Medium"),
    ("Greed for food was a key factor in the jackal's poor decision.", "True", "Medium"),
    ("The forest's natural environment contributed to the deceptive sounds.", "True", "Medium"),
    ("The moral applies only to animals and not to humans.", "False", "Medium"),
    ("The jackals' hard labour on tearing the dhol was completely wasted.", "True", "Medium"),
    ("The dhol continued to make music even after the leather was torn.", "False", "Medium"),
    ("Both Chapters 01 and 02 teach lessons about acting without thinking.", "True", "Medium"),
    ("The king's celebration has no connection to the jackal's story.", "False", "Medium"),
    ("A neutral approach to the sound would have been to investigate before acting.", "True", "Medium"),
    ("The jackals were wise to tear the dhol without looking inside first.", "False", "Medium"),
    ("The story teaches children the value of gathering complete information.", "True", "Medium"),
    ("The jackal showed excellent critical thinking throughout the story.", "False", "Medium"),
    ("Dramatic irony occurs because the reader knows the dhol is empty but the jackal does not.", "True", "Medium"),
    ("Panchatantra stories are no longer relevant in modern times.", "False", "Medium"),
    ("The jackal's reasoning demonstrates confirmation bias.", "True", "Hard"),
    ("The dhol symbolises deceptive appearances that seem promising but are hollow.", "True", "Hard"),
    ("The story promotes acting quickly without gathering evidence.", "False", "Hard"),
    ("Epistemic caution means verifying evidence before drawing conclusions.", "True", "Hard"),
    ("The jackal tested his hypothesis scientifically before acting.", "False", "Hard"),
    ("The empty dhol represents the futility of acting on unverified assumptions.", "True", "Hard"),
    ("Modern misinformation problems mirror the jackal's error of trusting unverified signals.", "True", "Hard"),
    ("The story builds scientific inquiry skills by showing the failure of untested hypotheses.", "True", "Hard"),
    ("The jackal's error was purely accidental with no preventable cause.", "False", "Hard"),
    ("Chapters 01 and 02 together establish 'Think + Investigate' as a decision-making framework.", "True", "Hard"),
]
tf_content = f"# True / False — Chapter 02: {CH_TITLE}\n\n> **Category**: True / False | **Total**: 50 Questions | **Marks**: 1 each\n\n---\n\n"
for idx, (stmt, ans, diff) in enumerate(tfs, 1):
    tf_content += f"### Question {idx}\n- **Question ID**: {CH_ID}_TF_{idx:03d}\n- **Difficulty**: {diff}\n- **Marks**: 1\n\n**Statement**: {stmt}\n\n- **Answer Key**: **{ans}**\n\n---\n\n"
with open(os.path.join(CH_DIR, "true_false.md"), "w", encoding="utf-8") as f: f.write(tf_content)

# ── 4. Short Answer (50) ──
sas = [
    ("What is the title and type of the story in Chapter 02?", "The title is 'The Jackal and the Dhol' and it is a Panchatantra Tale.", "Easy"),
    ("Why did the king hold a grand party?", "To celebrate his massive victory in a long-fought battle.", "Easy"),
    ("What happened to the dhol during the celebration?", "It fell and rolled into the nearby forest and got stuck in a tree.", "Easy"),
    ("Why did the dhol make sounds in the forest?", "Because tree branches were hitting it, producing a dham-dham sound.", "Easy"),
    ("Who heard the sound of the dhol?", "A jackal passing through the forest heard the sound.", "Easy"),
    ("What did the jackal think was inside the dhol?", "He thought a soft, delicious animal was stuck inside the dried leather.", "Easy"),
    ("Who did the jackal share his discovery with?", "He told his friend about the 'tasty animal' inside the dhol.", "Easy"),
    ("When did the jackals go to investigate the dhol?", "They went at night.", "Easy"),
    ("What did the jackals do to the dhol?", "They tore the leather on both sides with great effort.", "Easy"),
    ("What did the jackals find inside the dhol?", "They found nothing inside — the dhol was empty.", "Easy"),
    ("How did the jackals feel after their discovery?", "They felt disappointed because all their labour was wasted.", "Easy"),
    ("What is the moral of the story?", "Do not act without detailed information.", "Easy"),
    ("What does 'valiantly' mean?", "Bravely.", "Easy"),
    ("What does 'formidable' mean?", "Inspiring fear; very powerful or difficult to deal with.", "Easy"),
    ("What does 'conclude' mean?", "To form an opinion or judgement based on understanding.", "Easy"),
    ("What was the dhol originally used for?", "It was a musical drum used during the king's victory celebration.", "Easy"),
    ("How did the dhol end up in the forest?", "It fell during the celebration and rolled into the nearby forest.", "Easy"),
    ("What sound did the dhol make?", "It made a 'dham-dham' sound when branches hit it.", "Easy"),
    ("Why did the jackal think the animal inside was 'delicious'?", "He concluded from the soft dham-dham sound that the creature inside must be soft and tasty.", "Easy"),
    ("Did the jackal verify his assumption before acting?", "No, he acted without verifying and only discovered the truth after tearing the dhol.", "Easy"),
    ("What kind of battle did the king fight?", "A long, tough battle fought valiantly and tirelessly against a formidable enemy.", "Easy"),
    ("Why is this story called a Panchatantra Tale?", "Because it comes from the ancient Indian collection of fables known as Panchatantra.", "Easy"),
    ("What entertainment was arranged at the king's celebration?", "Dancing, singing, and music by many performers.", "Easy"),
    ("Where exactly did the dhol get stuck?", "In a tree, in a position where branches would hit it.", "Easy"),
    ("What was wasted because of the jackal's wrong assumption?", "Their hard physical labour of tearing the leather was completely wasted.", "Easy"),
    ("Explain why the jackal's reasoning was flawed.", "He assumed that the dham-dham sound meant a living creature was inside, but it was just branches hitting the drum leather.", "Medium"),
    ("How does greed contribute to the jackal's mistake?", "His greed for tasty food prevented him from carefully investigating the source of the sound first.", "Medium"),
    ("What could the jackal have done differently to avoid disappointment?", "He could have looked through holes, tapped the dhol, or smelled for food before tearing it apart.", "Medium"),
    ("Compare the jackal's error with a real-life example of acting on incomplete information.", "Like someone buying a product based on flashy advertising without reading reviews — the appearance was misleading.", "Medium"),
    ("How does the forest setting contribute to the jackal's confusion?", "The wind and branches created natural sounds that made the dhol seem alive, misleading the jackal.", "Medium"),
    ("What role does the jackal's friend play in the story?", "The friend trusted the jackal's claim without questioning it, making two animals invest effort in a wrong assumption.", "Medium"),
    ("How is dramatic irony used in this story?", "The reader understands the dhol is just a musical instrument, while the jackal believes it contains food.", "Medium"),
    ("What does the phrase 'all their labour got wasted' teach readers?", "It teaches that effort invested based on false assumptions leads to complete loss.", "Medium"),
    ("How does this story build critical thinking skills for students?", "It encourages students to question assumptions, seek evidence, and verify before committing to action.", "Medium"),
    ("Compare the moral of Chapter 02 with Chapter 01.", "Ch 01 says 'Think before you act'; Ch 02 says 'Do not act without detailed information' — both emphasise caution before action.", "Medium"),
    ("What is the significance of the jackals tearing 'both sides' of the leather?", "It shows they committed fully to a wrong course of action without pausing to reconsider.", "Medium"),
    ("How does this story demonstrate the concept of hypothesis testing?", "The jackal had a hypothesis (food inside) but never tested it — he committed fully and only learned the truth after.", "Medium"),
    ("Why did the jackals choose nighttime for their plan?", "Night provided cover and secrecy, showing they treated their wrong assumption as a serious hunting plan.", "Medium"),
    ("What would a wise jackal have done differently?", "A wise jackal would have investigated the sound source, looked inside the dhol, and verified before committing effort.", "Medium"),
    ("What emotional journey do the jackals go through in the story?", "Curiosity → excitement → anticipation → hard work → discovery → disappointment and regret.", "Medium"),
    ("Analyse how the dhol functions as a deceptive object in the story.", "The dhol produces sounds that mimic life but is actually hollow — representing how surface appearances can mislead.", "Hard"),
    ("Evaluate the philosophical depth of the moral for young learners.", "It introduces epistemic caution: the principle that knowledge must be verified before action, building foundational critical thinking.", "Hard"),
    ("How does the story warn against confirmation bias?", "The jackal heard what he wanted to hear (food) and ignored alternative explanations (instrument), demonstrating confirmation bias.", "Hard"),
    ("Synthesise the combined wisdom of Chapters 01 and 02.", "Ch 01: Think about consequences before acting. Ch 02: Gather complete information before acting. Together: Wisdom = Foresight + Evidence.", "Hard"),
    ("Draft a 4-line poem summarising Chapter 02.", "'A dhol in the forest went dham-dham-dham,\nThe jackal thought it held a feast so grand;\nHe tore it open — nothing there at all,\nNow think before you act, or you shall fall!'", "Hard"),
    ("Assess the relevance of this Panchatantra tale to modern information literacy.", "Just as the jackal trusted incomplete sensory data, people today often trust unverified online content — both need evidence-based verification.", "Hard"),
    ("Critique the jackal's decision-making process step by step.", "1. Heard sound (limited data). 2. Imagined food (unfounded). 3. Told friend (spread assumption). 4. Acted at night (secrecy). 5. Found nothing (consequence). Each step lacked verification.", "Hard"),
    ("How does the story build vocabulary and inference skills for Class 3?", "Introduces words like valiantly, formidable, conclude; requires inferring character motivations and evaluating outcomes.", "Hard"),
    ("Formulate a classroom activity based on this chapter.", "Give students sealed boxes with different objects inside; have them guess contents using only sound before opening — demonstrating the lesson of verification.", "Hard"),
    ("What is the ultimate lesson of Chapter 02 for young learners?", "Always verify before you act — investigate thoroughly, question your assumptions, and gather complete evidence before investing effort.", "Hard"),
]
sa_content = f"# Short Answer Questions — Chapter 02: {CH_TITLE}\n\n> **Category**: Short Answer | **Total**: 50 Questions | **Marks**: 2 each\n\n---\n\n"
for idx, (q, a, diff) in enumerate(sas, 1):
    sa_content += f"### Question {idx}\n- **Question ID**: {CH_ID}_SA_{idx:03d}\n- **Difficulty**: {diff}\n- **Marks**: 2\n\n**Question**: {q}\n\n- **Answer Key**: {a}\n\n---\n\n"
with open(os.path.join(CH_DIR, "short_answer.md"), "w", encoding="utf-8") as f: f.write(sa_content)

# ── 5. Long Answer (50) ──
las = [
    ("Narrate the complete story of 'The Jackal and the Dhol' in your own words.", "Once upon a time, a king won a long battle fought valiantly against a formidable enemy. To celebrate, he held a grand party with dancers, singers, and musicians. During the celebration, a dhol fell and rolled into the nearby forest. It got stuck in a tree where branches kept hitting it, producing a dham-dham sound.\n\nA jackal passing by heard the sound and observed the dhol from a distance. He wrongly concluded that a soft, delicious animal was trapped inside the dried leather. Excited, he told his friend about the 'tasty animal.' At night, they went together and tore the leather on both sides with great effort. But they found absolutely nothing inside — the dhol was hollow and empty. Disappointed, they realised all their labour was wasted. The moral: Do not act without detailed information.", "Easy", "Remembering"),
    ("Describe the character of the jackal and explain why he is considered foolish.", "The jackal is curious, greedy, and impulsive:\n- **Curious**: He investigated the strange sound in the forest.\n- **Greedy**: He immediately assumed the sound meant food without checking.\n- **Impulsive**: He told his friend and tore the dhol apart at night without verifying.\n- **Foolish**: He drew conclusions from incomplete evidence (just sound), never tested his assumption, and wasted his entire night's effort for nothing.", "Easy", "Understanding"),
    ("Explain the moral 'Do not act without detailed information' using examples from the story.", "The moral warns against hasty action based on assumptions. In the story, the jackal heard the dham-dham sound and assumed a delicious animal was inside. He never looked inside, smelled for food, or tapped the dhol to check. He committed great effort to tear the leather, only to find nothing. If he had gathered detailed information first, he would have saved his effort.", "Easy", "Understanding"),
    ("How did the dhol end up in the forest and start making sounds?", "During the king's grand victory celebration, one dhol fell and rolled into the nearby forest. It rolled from place to place and finally got stuck in a tree in such a position that the tree's branches would hit it and produce dham-dham sounds whenever the wind blew.", "Easy", "Remembering"),
    ("What is the significance of the king's celebration at the beginning of the story?", "The king's celebration sets up the entire plot. Without the victory party with music and performers, the dhol would never have fallen into the forest, and the jackal would never have been deceived by its sound. It serves as the inciting incident.", "Easy", "Analyzing"),
    ("Describe the effort the jackals put into tearing the dhol and what they discovered.", "The two jackals worked with great physical effort, tearing the dried leather on both sides of the dhol. After much labour, they succeeded in removing the leather — but found nothing inside. The dhol was completely hollow and empty. All their effort was wasted, and they were deeply disappointed.", "Easy", "Remembering"),
    ("Explain the meanings of the vocabulary words: Valiantly, Formidable, and Conclude.", "1. **Valiantly**: Bravely — the king fought the battle bravely.\n2. **Formidable**: Inspiring fear — the enemy was so powerful that it inspired fear.\n3. **Conclude**: To form an opinion based on understanding — the jackal concluded that food was inside the dhol.", "Easy", "Understanding"),
    ("Why did the jackal decide the sound meant food was inside?", "The jackal heard the continuous dham-dham sound from the dhol. He concluded that something soft was being hit inside, and imagined it must be a delicious animal trapped between the dried leather of the drum. His greed and imagination led him to this wrong conclusion.", "Easy", "Understanding"),
    ("What would have happened if the jackal had checked inside the dhol before tearing it?", "If the jackal had peeked through a hole or tapped the dhol to check, he would have discovered it was just a hollow drum with no animal inside. He would have saved himself and his friend a night of wasted labour.", "Easy", "Applying"),
    ("Summarise Chapter 02 in five key sentences.", "1. A king won a battle and held a grand celebration with music and dance.\n2. A dhol fell and rolled into the forest, where branches hit it and made sounds.\n3. A jackal heard the dham-dham and assumed a delicious animal was trapped inside.\n4. He and his friend tore the dhol's leather at night but found nothing inside.\n5. The moral: Do not act without detailed information.", "Easy", "Understanding"),
    ("What role does the jackal's friend play?", "The friend blindly trusts the jackal's claim about a tasty animal inside the dhol. He joins the effort without questioning the assumption, doubling the wasted labour. This shows how unverified information can mislead multiple people.", "Easy", "Understanding"),
    ("Why is the Panchatantra important for children's education?", "The Panchatantra uses engaging animal stories to teach practical life skills like critical thinking, caution, integrity, and decision-making. Its lessons about human behaviour are timeless and easy for young readers to understand and remember.", "Easy", "Evaluating"),
    ("Describe the emotional journey of the jackals throughout the story.", "The jackals start with curiosity (hearing the sound), move to excitement (imagining food), build anticipation (planning the nighttime mission), invest effort (tearing leather), and end with deep disappointment (finding nothing).", "Easy", "Analyzing"),
    ("Explain how sound can be deceptive in natural settings.", "In the forest, natural elements like wind, branches, and terrain can create sounds that resemble living creatures. The dhol's dham-dham was caused by branches, not an animal. This shows that sounds alone are unreliable evidence for conclusions.", "Easy", "Understanding"),
    ("Write a letter from the jackal to his friend apologising for the wasted effort.", "Dear Friend,\nI am truly sorry for leading you on a fool's errand last night. I heard a sound from the dhol and hastily assumed food was inside without checking. Because of my mistake, we both wasted our entire night tearing leather for nothing. I have learned that we must always verify our assumptions before acting. I promise to investigate properly next time.\nYour regretful friend,\nThe Jackal", "Easy", "Creating"),
    ("Explain why going at night did not help the jackals succeed.", "Going at night only provided secrecy but did not change the fundamental problem: there was no animal inside the dhol. No amount of stealth or effort could create food where none existed. The timing was irrelevant to their flawed assumption.", "Medium", "Analyzing"),
    ("Analyse how greed affects the jackal's reasoning throughout the story.", "Greed for food drives every step: it makes the jackal imagine food from mere sound, prevents him from investigating carefully, motivates him to recruit his friend, and pushes both into exhausting labour. Greed clouded his judgement at every decision point.", "Medium", "Analyzing"),
    ("Compare the jackal's story with the fable of 'The Fox and the Grapes'.", "Both characters act on desire without verification. The fox declares grapes 'sour' when he can't reach them (rationalisation); the jackal assumes food exists based on sound (false assumption). Both demonstrate flawed reasoning driven by desire.", "Medium", "Comparing"),
    ("How does the story demonstrate the scientific method's importance?", "Science requires: 1) Observation 2) Hypothesis 3) Testing 4) Conclusion. The jackal observed (heard sound), hypothesised (animal inside), but SKIPPED testing and went straight to action. The story demonstrates what happens when you skip the testing step.", "Medium", "Evaluating"),
    ("What would be a safe way to investigate strange sounds in a forest?", "1. Observe from a safe distance. 2. Look for visual evidence. 3. Approach cautiously. 4. Tap or test the object. 5. Only act after confirming the source. This systematic approach avoids wasted effort and potential danger.", "Medium", "Applying"),
    ("Discuss how this story builds vocabulary and inference skills.", "Vocabulary like 'valiantly', 'formidable', and 'conclude' expands word knowledge. Inference skills are built as students must deduce why the jackal was wrong, predict outcomes, and evaluate character motives from textual clues.", "Medium", "Evaluating"),
    ("How could a teacher use this story for a class discussion on fake news?", "The teacher could draw parallels: just as the jackal trusted one unreliable signal (sound), people trust unverified social media posts. Discussion would cover verifying sources, seeking multiple evidence types, and thinking critically before sharing or acting.", "Medium", "Applying"),
    ("Explain the concept of 'wasted labour' as shown in this story.", "Wasted labour occurs when significant effort is invested in a task based on wrong premises. The jackals spent an entire night tearing tough leather, only to find emptiness. The lesson: verify your premise before investing resources.", "Medium", "Understanding"),
    ("How does the story illustrate the difference between hearing and understanding?", "The jackal heard the sound but misunderstood its source. Hearing is passive; understanding requires analysis. The jackal failed to analyse and instead let his imagination fill the gap between sound and meaning.", "Medium", "Analyzing"),
    ("What makes the dhol's situation ironic in the context of the story?", "The dhol was meant to create joyful music at a celebration, but it ended up creating a deceptive sound that led to the jackal's disappointment. An instrument of joy became an instrument of deception.", "Medium", "Analyzing"),
    ("Describe the narrative structure (beginning, middle, end) of Chapter 02.", "**Beginning**: King wins battle, holds celebration, dhol falls into forest.\n**Middle**: Jackal hears sound, assumes food, tells friend, they tear the dhol at night.\n**End**: They find nothing inside, realise their labour was wasted, moral stated.", "Medium", "Analyzing"),
    ("What role does patience play in this story?", "The jackal was impatient — he rushed from hearing a sound to concluding food existed to acting. Patience would have allowed him to observe longer, consider alternatives, and avoid the mistake.", "Medium", "Evaluating"),
    ("Draft a dialogue between the two jackals after they find the dhol empty.", "Jackal 1: 'I cannot believe it! There is nothing inside!'\nJackal 2: 'We tore all the leather for nothing?'\nJackal 1: 'I was so sure the dham-dham meant something tasty...'\nJackal 2: 'Next time, let us LOOK before we tear. We should have checked first.'\nJackal 1: 'You are right. We have learned a hard lesson tonight.'", "Medium", "Creating"),
    ("How does this story prepare Class 3 students for evidence-based learning?", "By showing that conclusions based on one sense (hearing) without cross-checking (seeing, touching) lead to failure, it trains students to seek multiple evidence types before forming conclusions.", "Medium", "Evaluating"),
    ("What are three alternative explanations the jackal should have considered for the dham-dham sound?", "1. Wind or branches hitting a hollow object.\n2. A musical instrument left behind.\n3. Falling fruits or stones creating rhythmic sounds. Any of these would have been more accurate than 'a tasty animal'.", "Medium", "Analyzing"),
    ("Analyse the theme of deceptive appearances in the story.", "The dhol's sound created an appearance of life where none existed. This theme warns that surface-level perception can be deeply misleading. True understanding requires looking beyond appearances to verify reality.", "Hard", "Analyzing"),
    ("Evaluate the philosophical significance of the moral for developing societies.", "The moral 'Do not act without detailed information' is foundational to progress. Scientific advancement, governance, and personal growth all require evidence-based decision-making over impulsive action.", "Hard", "Evaluating"),
    ("Compare the jackal's cognitive error with common logical fallacies.", "The jackal commits: 1) Hasty generalisation (one sound = food). 2) Confirmation bias (only saw evidence supporting his desire). 3) Appeal to emotion (greed overriding logic). These are common human cognitive errors.", "Hard", "Analyzing"),
    ("Synthesise how Chapters 01, 02, and 03 together build a comprehensive wisdom framework.", "Ch 01: Think before acting (foresight). Ch 02: Gather information before acting (evidence). Ch 03: Don't fight among yourselves (unity). Together: Wisdom = Foresight + Evidence + Unity.", "Hard", "Synthesizing"),
    ("Design a classroom experiment that demonstrates the lesson of Chapter 02.", "Give students sealed boxes containing different objects. Have them listen to sounds, form hypotheses, then open to verify. Debrief on how many assumptions were wrong — teaching the value of verification.", "Hard", "Creating"),
    ("Critique the narrative effectiveness of using a dhol as the central deceptive object.", "The dhol is brilliant because: 1) It connects to Indian culture (recognisable). 2) Its hollow structure creates realistic deception. 3) Its association with celebration adds irony. 4) Tearing leather shows committed but wasted effort.", "Hard", "Evaluating"),
    ("How does the story model the 'observe → hypothesise → test → conclude' cycle?", "The jackal observed (heard sound) and hypothesised (food inside) but FAILED to test before concluding and acting. The story is a cautionary tale about skipping the testing step in the scientific method.", "Hard", "Analyzing"),
    ("Assess the cross-cultural applicability of the moral.", "The lesson 'verify before acting' transcends cultures. Whether in Indian Panchatantra, Aesop's Fables, or modern decision science, the principle of evidence-based action is universally valued.", "Hard", "Evaluating"),
    ("Write a short book review of Chapter 02 for a school magazine.", "'The Jackal and the Dhol' is a captivating Panchatantra tale where a curious jackal mistakes a drum's sound for trapped food. With vivid imagery and a powerful moral about verification, it teaches young readers that assumptions without evidence lead to wasted effort. A must-read for budding critical thinkers!'", "Hard", "Creating"),
    ("Synthesise the ultimate lesson of Chapter 02 into a life motto.", "Verify before you act: investigate thoroughly, question every assumption, seek multiple evidence sources, and only commit effort after confirming reality matches expectation.", "Hard", "Synthesizing"),
]
la_content = f"# Long Answer Questions — Chapter 02: {CH_TITLE}\n\n> **Category**: Long Answer | **Total**: 50 Questions | **Marks**: 5 each\n\n---\n\n"
for idx, (q, a, diff, bloom) in enumerate(las, 1):
    la_content += f"### Question {idx}\n- **Question ID**: {CH_ID}_LA_{idx:03d}\n- **Difficulty**: {diff}\n- **Bloom Level**: {bloom}\n- **Marks**: 5\n\n**Question**: {q}\n\n- **Answer Key**: {a}\n\n---\n\n"
with open(os.path.join(CH_DIR, "long_answer.md"), "w", encoding="utf-8") as f: f.write(la_content)

# ── 6. Extract Based (50 = 10 sets × 5 Qs) ──
extracts = [
    ("Once upon a time, a king fought a long battle valiantly and tirelessly against a formidable enemy. Finally, the king won the long-fought battle.",
     [("How did the king fight the battle?", "Valiantly and tirelessly.", "Easy"),
      ("What kind of enemy did the king fight?", "A formidable enemy.", "Easy"),
      ("What does 'valiantly' mean?", "Bravely.", "Easy"),
      ("What does 'formidable' mean?", "Inspiring fear; very powerful.", "Easy"),
      ("What was the outcome of the battle?", "The king won the long-fought battle.", "Easy")]),
    ("To celebrate his massive victory, he decided to hold a grand party for all his subjects. He called many performers to entertain the attendees with dancing, singing and music.",
     [("Why did the king hold a grand party?", "To celebrate his massive victory.", "Easy"),
      ("Who was invited to the party?", "All his subjects.", "Easy"),
      ("What entertainment was arranged?", "Dancing, singing, and music by many performers.", "Easy"),
      ("What does 'massive' suggest about the victory?", "It was a very big and significant win.", "Medium"),
      ("What is the purpose of celebrations after a victory?", "To share joy, reward effort, and unite people.", "Medium")]),
    ("During this celebration, one dhol fell and rolled into the nearby forest. It rolled from one place to another and ultimately got stuck in a tree.",
     [("What fell during the celebration?", "A dhol.", "Easy"),
      ("Where did the dhol roll to?", "Into the nearby forest.", "Easy"),
      ("Where did the dhol finally get stuck?", "In a tree.", "Easy"),
      ("What does 'ultimately' mean?", "Finally; in the end.", "Medium"),
      ("How does this event connect to the jackal's story?", "The stuck dhol produces sounds that deceive the jackal.", "Medium")]),
    ("The branches would hit the dhol and make sounds. After some time, a jackal passed from that place and heard the sound of the dhol.",
     [("What caused the dhol to make sounds?", "Tree branches hitting the dhol.", "Easy"),
      ("Who heard the sound?", "A jackal passing through the forest.", "Easy"),
      ("Was the sound made by a living creature?", "No, it was caused by tree branches.", "Easy"),
      ("Why might the sound be confusing for an animal?", "Because the rhythmic sound could resemble a living creature's movement.", "Medium"),
      ("What should the jackal have done before assuming?", "Investigated the source of the sound more carefully.", "Medium")]),
    ("He observed it from a distance for some time and decided that it was not a harmful animal which was stuck inside the drum. And after hearing the dham-dham of the dhol concluded that it must be very soft and delicious to eat.",
     [("How long did the jackal observe the dhol?", "For some time, from a distance.", "Easy"),
      ("What sound did the dhol make?", "Dham-dham.", "Easy"),
      ("What did the jackal conclude about the sound?", "That a soft, delicious animal was inside.", "Easy"),
      ("What reasoning error did the jackal make?", "He assumed sound = food without any visual or physical evidence.", "Medium"),
      ("How does this demonstrate confirmation bias?", "The jackal interpreted ambiguous evidence to match his desire for food.", "Hard")]),
    ("He went back to his friend and told him that there was a tasty animal stuck between the dried leather of the dhol.",
     [("Who did the jackal tell about his discovery?", "His friend.", "Easy"),
      ("What did the jackal claim was inside?", "A tasty animal stuck between dried leather.", "Easy"),
      ("Was the jackal's claim accurate?", "No, the dhol was actually empty inside.", "Easy"),
      ("What problem arises from sharing unverified information?", "It spreads misinformation and causes others to waste effort too.", "Medium"),
      ("How does this relate to the danger of rumours?", "Like rumours, the jackal's claim was unverified but led to action based on trust.", "Hard")]),
    ("At night they went to catch the animal inside the dhol. They started tearing the leather on both sides with great effort.",
     [("When did the jackals go to the dhol?", "At night.", "Easy"),
      ("What did they do to the dhol?", "They started tearing the leather on both sides.", "Easy"),
      ("How much effort did they use?", "Great effort.", "Easy"),
      ("Why did they choose nighttime?", "For secrecy and cover while they hunted the supposed animal.", "Medium"),
      ("What does 'great effort' suggest about their commitment?", "They were fully invested in a plan based on a false assumption.", "Medium")]),
    ("Finally, they succeeded in tearing the leather away from the dhol but found nothing inside. They became disappointed after realising that all their labour got wasted.",
     [("What did the jackals find after tearing the leather?", "Nothing — the dhol was empty.", "Easy"),
      ("How did the jackals feel?", "Disappointed.", "Easy"),
      ("What was wasted?", "All their labour and effort.", "Easy"),
      ("What could they have done to avoid this?", "Checked inside the dhol before tearing it apart.", "Medium"),
      ("What life lesson does 'wasted labour' teach?", "Effort based on false premises leads to complete loss.", "Hard")]),
    ("Moral of the Story: Do not act without detailed information.",
     [("What is the moral of the story?", "Do not act without detailed information.", "Easy"),
      ("Why is detailed information important before acting?", "It prevents wasted effort and wrong decisions.", "Medium"),
      ("How did the jackal violate this moral?", "He acted based on sound alone without gathering any detailed evidence.", "Medium"),
      ("Give a real-life example where this moral applies.", "Buying something expensive without reading reviews or checking quality first.", "Medium"),
      ("How does this moral connect to critical thinking?", "Critical thinking requires evidence verification before conclusions — exactly what this moral teaches.", "Hard")]),
    ("The jackal heard the dham-dham sound and concluded it must be soft and delicious to eat... but found nothing inside.",
     [("What was the jackal's hypothesis?", "That a soft, delicious animal was inside the dhol.", "Easy"),
      ("Was the hypothesis correct?", "No, the dhol was empty.", "Easy"),
      ("What step of scientific thinking did the jackal skip?", "Testing his hypothesis before acting on it.", "Medium"),
      ("How does this story teach the importance of testing before concluding?", "The jackal would have saved all effort if he had tested (looked inside) before committing.", "Medium"),
      ("Synthesise the ultimate learning from this chapter.", "Verify assumptions through evidence before investing effort — assumptions alone lead to disappointment.", "Hard")]),
]
ext_content = f"# Extract Based Questions — Chapter 02: {CH_TITLE}\n\n> **Category**: Extract Based | **Total**: 10 Extract Sets (50 Questions) | **Marks**: 1 each\n\n---\n\n"
q_ctr = 1
for si, (ext, qs) in enumerate(extracts, 1):
    ext_content += f"## Extract Set {si}\n\n> *\"{ext}\"*\n\n---\n"
    for q, a, diff in qs:
        ext_content += f"\n### Question {q_ctr}\n- **Question ID**: {CH_ID}_EXT_{q_ctr:03d}\n- **Difficulty**: {diff}\n- **Marks**: 1\n\n**Question**: {q}\n\n- **Answer Key**: {a}\n"
        q_ctr += 1
    ext_content += "\n\n---\n\n"
with open(os.path.join(CH_DIR, "extract_based.md"), "w", encoding="utf-8") as f: f.write(ext_content)

print(f"SUCCESS: Generated all 6 category files (300 Qs) for Chapter 02 in {CH_DIR}")
