r"""
Generates 300 questions across 6 categories for Chapter 03 (Two Cats and the Monkey) — Book 3
"""
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CH_DIR = os.path.join(BASE_DIR, "question_bank", "chapter_03")
os.makedirs(CH_DIR, exist_ok=True)
CH_ID = "BK03_CH03"
CH_TITLE = "Two Cats and the Monkey"

# ── 1. MCQs (50) ──
mcqs = [
    ("What did the two cats find on the street?","(A) A roti","(B) A fish","(C) A cheese","(D) A bread loaf","(A)","They found a roti lying on the street.","Easy","Remembering","Discovery"),
    ("What is 'Two Cats and the Monkey' based on?","(A) A Panchatantra Tale","(B) A Greek Myth","(C) A Modern Novel","(D) A Science Report","(A)","It is a Panchatantra Tale.","Easy","Remembering","Genre"),
    ("What were the two cats doing before they found the roti?","(A) Frolicking on the road","(B) Sleeping in a house","(C) Fishing in a pond","(D) Climbing a mountain","(A)","They were frolicking on the road.","Easy","Remembering","Activity"),
    ("What did the cats decide to do with the roti?","(A) Share it equally between themselves","(B) Give it to the monkey","(C) Throw it away","(D) Hide it in a tree","(A)","They decided to share equally.","Easy","Remembering","Decision"),
    ("Why did the cats start arguing?","(A) Each thought the other got the bigger part","(B) They wanted different flavours","(C) They could not find the roti","(D) A dog stole the roti","(A)","Each claimed the other got a bigger piece.","Easy","Remembering","Conflict"),
    ("Who did the cats choose as their judge?","(A) A monkey","(B) A dog","(C) A human","(D) A bird","(A)","They chose a monkey sitting on a wall.","Easy","Remembering","Judge"),
    ("Where was the monkey sitting when the cats found him?","(A) On a wall","(B) In a tree","(C) On the road","(D) In the river","(A)","The monkey was sitting on a wall.","Easy","Remembering","Location"),
    ("Had the monkey observed the cats' fight?","(A) Yes, he had been watching for some time","(B) No, he was sleeping","(C) No, he just arrived","(D) He was reading a book","(A)","He had observed their fight.","Easy","Remembering","Observation"),
    ("What was the monkey really looking for?","(A) An opportunity to grab the roti for himself","(B) A chance to help the cats","(C) A new home","(D) Other monkeys to play with","(A)","He wanted to grab the roti for himself.","Easy","Understanding","Motive"),
    ("How did the monkey pretend to judge the roti?","(A) He lifted both parts, compared them, and took bites from each","(B) He weighed them on a scale","(C) He measured them with a ruler","(D) He asked other animals for opinions","(A)","He lifted, compared, and took bites.","Easy","Remembering","Method"),
    ("What excuse did the monkey give for taking bites?","(A) He said one portion was bigger and needed to be made equal","(B) He was testing for poison","(C) He was very hungry and asked permission","(D) He wanted to check the taste for quality","(A)","He said one portion was bigger.","Easy","Remembering","Excuse"),
    ("What happened to the roti in the end?","(A) The monkey gobbled up the entire roti","(B) The cats shared it equally","(C) It fell into a river","(D) A bird took it away","(A)","The monkey ate the entire roti.","Easy","Remembering","Outcome"),
    ("How did the cats watch the monkey eat their roti?","(A) Helplessly","(B) Happily","(C) Angrily and fought the monkey","(D) They did not notice","(A)","They could only look helplessly.","Easy","Remembering","Reaction"),
    ("What did the monkey do after eating all the roti?","(A) Jumped back on the wall and vanished","(B) Thanked the cats","(C) Fell asleep","(D) Gave them another roti","(A)","He jumped on the wall and vanished.","Easy","Remembering","Departure"),
    ("Did the cats get any roti to eat?","(A) No, they did not get even a single bite","(B) Yes, they each got half","(C) Yes, the monkey gave them crumbs","(D) They found another roti","(A)","They did not get even a single bite.","Easy","Remembering","Final Share"),
    ("What did the cats realise at the end?","(A) They were foolish to fight and trust a stranger","(B) Monkeys are the best judges","(C) Fighting is fun","(D) They should have hidden the roti","(A)","Foolish to fight and trust a stranger.","Easy","Understanding","Lesson Learned"),
    ("What is the moral of the story?","(A) Fighting amongst yourselves allows others to take advantage of you","(B) Always trust monkeys","(C) Never share food","(D) Fighting makes you stronger","(A)","Fighting allows others to take advantage.","Easy","Remembering","Moral"),
    ("What does 'frolicking' mean?","(A) To behave in a playful way","(B) To fight aggressively","(C) To sleep deeply","(D) To swim in water","(A)","Frolicking means behaving playfully.","Easy","Understanding","Vocabulary"),
    ("What does 'neutral' mean?","(A) Not supporting either side in an argument","(B) Very angry","(C) Extremely happy","(D) Supporting one side only","(A)","Not supporting either side.","Easy","Understanding","Vocabulary"),
    ("What does 'gobbled up' mean?","(A) Ate quickly and greedily","(B) Threw away carefully","(C) Cooked slowly","(D) Shared generously","(A)","Ate quickly and greedily.","Easy","Understanding","Vocabulary"),
    ("Why did the cats need a judge?","(A) They could not agree on whether the pieces were equal","(B) They wanted entertainment","(C) It was a rule of the village","(D) The monkey offered himself","(A)","Could not agree on equality of pieces.","Easy","Understanding","Need for Judge"),
    ("How did the first cat describe the roti division?","(A) The second cat got the bigger part which was unfair","(B) The roti was perfectly equal","(C) Both pieces were too small","(D) The roti was burnt","(A)","Said the other got the bigger, unfair part.","Easy","Remembering","Complaint"),
    ("What did the second cat say in response?","(A) That it was untrue — she did not get the bigger part","(B) She agreed and gave some back","(C) She ran away with the roti","(D) She asked a dog to judge","(A)","Said it was untrue.","Easy","Remembering","Counter-claim"),
    ("Were the cats friends before the argument?","(A) Yes, they were friends","(B) No, they were enemies","(C) They had never met before","(D) They were siblings","(A)","The cats were friends.","Easy","Remembering","Relationship"),
    ("What title is given to Chapter 03?","(A) Two Cats and the Monkey","(B) The Jackal and the Dhol","(C) The Foolish Pandit","(D) Fountain Pen","(A)","Two Cats and the Monkey.","Easy","Remembering","Title"),
    # Medium
    ("Why did the monkey readily agree to be the judge?","(A) He saw an opportunity to cheat the cats and eat the roti himself","(B) He was a trained judge","(C) He genuinely wanted to help","(D) The cats forced him","(A)","He wanted to cheat them and eat the roti.","Medium","Analyzing","Monkey's Motive"),
    ("How does the monkey exploit the cats' dispute for his own benefit?","(A) By pretending to make portions equal while actually eating the entire roti bite by bite","(B) By running away immediately","(C) By calling other animals","(D) By giving them advice","(A)","Pretending to equalize while eating everything.","Medium","Analyzing","Exploitation"),
    ("What is the irony in the cats choosing the monkey as a 'neutral judge'?","(A) The judge was never neutral — he was a self-interested cheat who used their trust","(B) The monkey was actually fair","(C) The cats won in the end","(D) There is no irony","(A)","The judge was self-interested, not neutral.","Medium","Analyzing","Irony"),
    ("How does internal fighting weaken a group according to this story?","(A) When friends fight amongst themselves, they become vulnerable to exploitation by outsiders","(B) Fighting makes them physically stronger","(C) Fighting has no effect on the group","(D) Fighting helps them find better food","(A)","Internal conflict makes groups vulnerable.","Medium","Evaluating","Theme Analysis"),
    ("What could the cats have done instead of fighting?","(A) Trusted each other, accepted the slight difference, or measured the pieces together","(B) Thrown the roti away","(C) Given the entire roti to the monkey","(D) Eaten the roti without sharing","(A)","Trusted each other or measured together.","Medium","Applying","Alternative Action"),
    ("Compare the monkey's cunning with the jackal's foolishness in Chapter 02.","(A) The monkey used cleverness to exploit others; the jackal used foolishness that hurt only himself","(B) Both were equally foolish","(C) Both were equally wise","(D) Neither story has animal characters","(A)","Monkey: clever exploitation. Jackal: self-harming foolishness.","Medium","Comparing","Cross-Chapter"),
    ("What lesson does the story teach about trusting strangers with personal disputes?","(A) Strangers may have their own agenda and exploit your vulnerability during disputes","(B) Always trust strangers completely","(C) Strangers always give the best advice","(D) Personal disputes should always involve strangers","(A)","Strangers may exploit vulnerability.","Medium","Evaluating","Trust Lesson"),
    ("How does the monkey maintain his deception throughout the judging process?","(A) By repeatedly claiming one piece is bigger, taking a bite each time, creating an endless cycle until the roti is gone","(B) By weighing pieces on a scale","(C) By dividing fairly","(D) By asking the cats to close their eyes","(A)","Endless cycle of 'one is bigger' + bites.","Medium","Analyzing","Deception Technique"),
    ("Why were the cats 'helpless' while the monkey ate their roti?","(A) They had given him authority as judge and could not challenge his method","(B) The monkey was too strong","(C) They fell asleep","(D) A cage trapped them","(A)","They had ceded authority to him.","Medium","Understanding","Power Dynamic"),
    ("What does 'vanished from there' tell us about the monkey's character?","(A) He had no guilt or loyalty — he took what he wanted and disappeared without remorse","(B) He was a magician","(C) He went home to share the roti","(D) He felt sorry and came back later","(A)","No guilt, took what he wanted and left.","Medium","Analyzing","Character Analysis"),
    ("How does this story apply to real-world situations of sibling rivalry?","(A) When siblings fight over things, parents or others may end up deciding, and both may lose out","(B) Siblings should always fight","(C) Siblings never share anything","(D) This story only applies to animals","(A)","Sibling fights can result in both losing.","Medium","Applying","Real-World Application"),
    ("What quality did the cats lack that led to their loss?","(A) Trust in each other and ability to compromise","(B) Physical strength","(C) Speed and agility","(D) Intelligence about cooking","(A)","Lacked trust and compromise ability.","Medium","Evaluating","Character Weakness"),
    ("Why is the moral 'Fighting allows others to take advantage' universally important?","(A) In any group — family, school, nation — internal conflict creates opportunities for outsiders to exploit","(B) It only applies to cats","(C) Fighting is always good","(D) It has no modern relevance","(A)","Universal: internal conflict invites exploitation.","Medium","Evaluating","Universal Relevance"),
    ("How does the story show that a small disagreement can lead to total loss?","(A) A tiny difference in roti size escalated to a fight, which led to losing the entire roti to the monkey","(B) The cats gained more roti","(C) The disagreement was resolved peacefully","(D) Nothing was lost","(A)","Small difference → fight → total loss.","Medium","Analyzing","Escalation"),
    ("What is the significance of the cats being friends at the start?","(A) It emphasises that even friends can lose everything when they let disputes override their bond","(B) It has no significance","(C) It means they were never close","(D) It proves friends should never share food","(A)","Even friends lose when disputes override bonds.","Medium","Analyzing","Friendship Theme"),
    # Hard
    ("Analyse the power dynamics between the cats and the monkey.","(A) The cats voluntarily surrendered their power to the monkey by making him judge, enabling their own exploitation","(B) The monkey had legal authority","(C) The cats were physically weaker","(D) There were no power dynamics","(A)","Cats surrendered power voluntarily.","Hard","Analyzing","Power Dynamics"),
    ("Evaluate the story's commentary on third-party intervention in personal disputes.","(A) Third parties may have hidden agendas; resolving disputes internally is safer than ceding control to outsiders","(B) Third parties always help","(C) You should never resolve disputes yourself","(D) The story has no commentary on this","(A)","Third parties may have hidden agendas.","Hard","Evaluating","Social Commentary"),
    ("Compare this story with the English proverb 'United we stand, divided we fall'.","(A) Both convey that internal division leads to collapse and exploitation, while unity preserves strength and resources","(B) They teach opposite lessons","(C) The proverb is about architecture","(D) There is no connection","(A)","Internal division → collapse; unity → strength.","Hard","Comparing","Proverbial Parallel"),
    ("Synthesise how Chapters 01-03 build a progressive wisdom curriculum.","(A) Ch01: Think before acting. Ch02: Gather info before acting. Ch03: Stay united, don't let disputes invite exploitation. Progressive: Thought → Evidence → Unity","(B) They teach only about animals","(C) They repeat the same lesson","(D) They have no connection","(A)","Progressive: Thought → Evidence → Unity.","Hard","Synthesizing","Curriculum Design"),
    ("Critique the monkey's ethics from a moral philosophy perspective.","(A) The monkey represents opportunistic self-interest without regard for justice or fairness — a cautionary example of unchecked selfishness","(B) The monkey was ethically correct","(C) Ethics do not apply to animals","(D) The monkey was the true victim","(A)","Opportunistic self-interest, cautionary example.","Hard","Evaluating","Ethical Critique"),
    ("How does this story function as an allegory for political exploitation?","(A) When citizens fight amongst themselves, corrupt leaders (the monkey) exploit their division for personal gain","(B) It is about cooking","(C) It has no political meaning","(D) The monkey represents democracy","(A)","Internal citizen conflict enables corrupt exploitation.","Hard","Analyzing","Political Allegory"),
    ("Design a role-play activity for Class 3 students based on this chapter.","(A) Three students play the two cats and the monkey; they act out the dispute, the judging, and the loss, then discuss how they could have resolved it differently","(B) Students just read the story silently","(C) Students draw pictures of monkeys","(D) Students memorise the story word by word","(A)","Role-play dispute, judging, loss; discuss alternatives.","Hard","Creating","Pedagogical Design"),
    ("Assess how the story develops emotional intelligence in young readers.","(A) It teaches recognising exploitation, valuing compromise, controlling anger during disputes, and choosing trustworthy mediators","(B) It only teaches reading skills","(C) It has no emotional content","(D) It makes children afraid of monkeys","(A)","Recognise exploitation, value compromise, control anger.","Hard","Evaluating","Emotional Intelligence"),
    ("Formulate the ultimate lesson of Chapter 03 as a life principle.","(A) Unity and trust between friends is more valuable than any material possession — resolve disputes internally before outsiders exploit your division","(B) Always let strangers solve your problems","(C) Never share anything with anyone","(D) Fighting is the best way to solve problems","(A)","Unity > material possession; resolve disputes internally.","Hard","Creating","Life Principle"),
    ("Synthesise a classroom discussion comparing all three Panchatantra tales (Ch 01-03).","(A) All three teach caution: Ch01 (think before acting), Ch02 (verify before acting), Ch03 (unite before outsiders exploit) — together they build comprehensive wisdom for young learners","(B) They are unrelated stories","(C) Only Chapter 01 has a moral","(D) None of them are Panchatantra tales","(A)","Three pillars: Think + Verify + Unite.","Hard","Synthesizing","Comparative Discussion"),
]

mcq_content = f"# MCQs — Chapter 03: {CH_TITLE}\n\n> **Category**: Multiple Choice Questions | **Total**: 50 Questions | **Marks**: 1 each\n\n---\n\n"
for idx, (q,a,b,c,d,ans,exp,diff,bloom,topic) in enumerate(mcqs,1):
    mcq_content += f"### Question {idx}\n- **Question ID**: {CH_ID}_MCQ_{idx:03d}\n- **Difficulty**: {diff}\n- **Bloom Level**: {bloom}\n- **Topic**: {topic}\n- **Marks**: 1\n\n**Question**: {q}\n\n- {a}\n- {b}\n- {c}\n- {d}\n\n- **Answer Key**: **{ans}** — {exp}\n\n---\n\n"
with open(os.path.join(CH_DIR, "mcqs.md"), "w", encoding="utf-8") as f: f.write(mcq_content)

# ── 2. Fill in the Blanks (50) ──
fibs = [
    ("Two cats found a _______ lying on the street.","roti","Easy"),("The cats were friends so they decided to _______ the roti equally.","share","Easy"),("The cats tore the roti into _______ parts.","two","Easy"),("The first cat complained the second got the _______ part.","bigger","Easy"),("The second cat said that claim was _______.","untrue","Easy"),("The cats became tired of _______ with each other.","arguing","Easy"),("They decided to find a _______ judge.","neutral","Easy"),("They found a _______ sitting on a wall.","monkey","Easy"),("The monkey had _______ their fight for some time.","observed","Easy"),("The monkey was looking for an opportunity to _______ the roti.","grab","Easy"),("He readily _______ to be the judge.","agreed","Easy"),("The monkey lifted the two _______ of roti.","parts","Easy"),("He _______ to compare them and took a bite.","pretended","Easy"),("The monkey said 'This portion was _______'.","bigger","Easy"),("He kept taking _______ from both pieces.","bites","Easy"),("The foolish cats could only look at him _______.","helplessly","Easy"),("Within minutes, the monkey _______ up the full roti.","gobbled","Easy"),("The monkey jumped back on the _______ and vanished.","wall","Easy"),("The cats did not get even a _______ bite.","single","Easy"),("They realised they were _______ to fight amongst themselves.","foolish","Easy"),("They were also foolish to trust a _______.","stranger","Easy"),("The moral is: Fighting allows others to take _______ of you.","advantage","Easy"),("Frolicking means to behave in a _______ way.","playful","Easy"),("Neutral means not supporting _______ side.","either","Easy"),("The roti was lying on the _______.","street","Easy"),
    ("The cats' internal _______ made them vulnerable to exploitation.","conflict","Medium"),("The monkey exploited their _______ to serve his own greed.","dispute","Medium"),("Trust and _______ could have saved the cats' roti.","compromise","Medium"),("The monkey's method involved an _______ cycle of fake comparisons.","endless","Medium"),("Ceding decision-making _______ to an outsider proved costly.","authority","Medium"),("A small disagreement _______ into a total loss.","escalated","Medium"),("Internal fighting weakens any _______ against outside threats.","group","Medium"),("The cats voluntarily _______ their power to the monkey.","surrendered","Medium"),("Resolving disputes _______ is safer than involving strangers.","internally","Medium"),("The monkey had zero _______ or fairness in his judging.","impartiality","Medium"),("Mutual _______ between the cats could have prevented the loss.","trust","Medium"),("The monkey's opportunism is a cautionary example of _______.","selfishness","Medium"),("The proverb 'United we stand, _______ we fall' captures this moral.","divided","Medium"),("Third-party mediators should be chosen for their _______, not convenience.","integrity","Medium"),("Emotional _______ helps children resolve disputes without external help.","intelligence","Medium"),
    ("The monkey represents _______ self-interest in moral philosophy.","opportunistic","Hard"),("The cats' loss is an allegory for _______ exploitation.","political","Hard"),("Chapters 01-03 build a progressive wisdom curriculum: Think → Verify → _______.","Unite","Hard"),("The monkey's behaviour demonstrates unchecked _______ without conscience.","greed","Hard"),("The story develops skills in recognising _______ and valuing compromise.","exploitation","Hard"),("Unity and trust are more valuable than any _______ possession.","material","Hard"),("Internal division creates _______ for outsiders to exploit.","opportunities","Hard"),("The Panchatantra's enduring relevance proves human _______ patterns are constant.","behaviour","Hard"),("The story's power dynamics show how voluntarily ceded authority enables _______.","manipulation","Hard"),("Chapter 03 integrates moral reasoning, vocabulary, and social-emotional _______.","learning","Hard"),
]
fib_content = f"# Fill in the Blanks — Chapter 03: {CH_TITLE}\n\n> **Category**: Fill in the Blanks | **Total**: 50 Questions | **Marks**: 1 each\n\n---\n\n"
for idx,(s,a,d) in enumerate(fibs,1):
    fib_content += f"### Question {idx}\n- **Question ID**: {CH_ID}_FIB_{idx:03d}\n- **Difficulty**: {d}\n- **Marks**: 1\n\n**Question**: {s}\n\n- **Answer Key**: **{a}**\n\n---\n\n"
with open(os.path.join(CH_DIR, "fill_in_the_blanks.md"), "w", encoding="utf-8") as f: f.write(fib_content)

# ── 3. True/False (50) ──
tfs = [
    ("Two cats found a roti lying on the street.","True","Easy"),("The cats were enemies before finding the roti.","False","Easy"),("The cats decided to share the roti equally.","True","Easy"),("Both cats agreed that the roti was divided perfectly.","False","Easy"),("The first cat said the second got the bigger part.","True","Easy"),("The cats chose a dog as their judge.","False","Easy"),("A monkey was sitting on a wall nearby.","True","Easy"),("The monkey had not seen the cats' fight at all.","False","Easy"),("The monkey wanted to help the cats fairly.","False","Easy"),("The monkey was looking for an opportunity to grab the roti.","True","Easy"),("The monkey lifted both parts of the roti.","True","Easy"),("The monkey used a weighing scale to measure the pieces.","False","Easy"),("The monkey took bites from the roti claiming each piece was bigger.","True","Easy"),("The cats fought the monkey and took back their roti.","False","Easy"),("The monkey gobbled up the entire roti.","True","Easy"),("The cats got at least a small bite each.","False","Easy"),("The monkey vanished after eating all the roti.","True","Easy"),("The cats learned they were foolish to fight and trust a stranger.","True","Easy"),("The moral is 'Fighting allows others to take advantage of you'.","True","Easy"),("'Frolicking' means to fight aggressively.","False","Easy"),("'Neutral' means not supporting either side.","True","Easy"),("The roti was found in a river.","False","Easy"),("The monkey pretended to be a fair judge.","True","Easy"),("The cats shared the roti happily in the end.","False","Easy"),("Chapter 03 is a Panchatantra Tale.","True","Easy"),
    ("The monkey exploited the cats' internal dispute for personal gain.","True","Medium"),("The cats could have avoided loss by compromising instead of fighting.","True","Medium"),("Internal conflict strengthens a group against outside threats.","False","Medium"),("The monkey was genuinely neutral and fair in his judgement.","False","Medium"),("Trusting strangers with personal disputes always leads to fair outcomes.","False","Medium"),("The story teaches that unity is more valuable than material possessions.","True","Medium"),("A small disagreement between the cats escalated into total loss.","True","Medium"),("The monkey's method of comparing pieces was honest and transparent.","False","Medium"),("The proverb 'United we stand, divided we fall' matches this story's moral.","True","Medium"),("The cats voluntarily gave up their decision-making power to the monkey.","True","Medium"),("Resolving disputes internally is always worse than involving outsiders.","False","Medium"),("The cats demonstrated good emotional intelligence by fighting over the roti.","False","Medium"),("The monkey showed that outsiders can exploit internal divisions.","True","Medium"),("The story has no relevance to modern human relationships.","False","Medium"),("Compromise would have saved the cats from losing their entire roti.","True","Medium"),
    ("The monkey represents opportunistic self-interest in the story.","True","Hard"),("The story functions as a political allegory about exploitation of divided groups.","True","Hard"),("Chapters 01-03 together build the framework: Think → Verify → Unite.","True","Hard"),("The monkey's vanishing symbolises the shamelessness of opportunistic exploitation.","True","Hard"),("The story encourages children to always fight over food.","False","Hard"),("The Panchatantra's moral about internal division is irrelevant in the 21st century.","False","Hard"),("Third-party mediators should always be chosen for integrity, not convenience.","True","Hard"),("The story develops emotional intelligence skills in young readers.","True","Hard"),("The cats' helplessness during the monkey's feast shows loss of agency due to ceded authority.","True","Hard"),("Chapter 03 integrates moral reasoning, vocabulary, and social-emotional learning.","True","Hard"),
]
tf_content = f"# True / False — Chapter 03: {CH_TITLE}\n\n> **Category**: True / False | **Total**: 50 Questions | **Marks**: 1 each\n\n---\n\n"
for idx,(s,a,d) in enumerate(tfs,1):
    tf_content += f"### Question {idx}\n- **Question ID**: {CH_ID}_TF_{idx:03d}\n- **Difficulty**: {d}\n- **Marks**: 1\n\n**Statement**: {s}\n\n- **Answer Key**: **{a}**\n\n---\n\n"
with open(os.path.join(CH_DIR, "true_false.md"), "w", encoding="utf-8") as f: f.write(tf_content)

# ── 4. Short Answer (50) ──
sas = [
    ("What did the two cats find on the street?","They found a roti lying on the street.","Easy"),("What were the cats doing before they found the roti?","They were frolicking (playing) on the road.","Easy"),("How did the cats try to divide the roti?","They tore the roti into two pieces to share equally.","Easy"),("Why did the cats start arguing?","Each cat thought the other got the bigger part, which was unfair.","Easy"),("Who did the cats approach to settle their argument?","They approached a monkey sitting on a wall.","Easy"),("Had the monkey seen the cats fighting?","Yes, he had been observing their fight for some time.","Easy"),("What was the monkey's real intention?","He was looking for an opportunity to grab the roti for himself.","Easy"),("How did the monkey pretend to judge?","He lifted both parts, compared them, and took bites claiming one was bigger.","Easy"),("What happened to the roti?","The monkey gobbled up the entire roti within minutes.","Easy"),("How did the cats react while the monkey ate?","They could only look at him helplessly.","Easy"),("What did the monkey do after eating the roti?","He jumped back on the wall and vanished.","Easy"),("Did the cats get any roti?","No, they did not get even a single bite.","Easy"),("What did the cats realise at the end?","They were foolish to fight amongst themselves and trust a stranger.","Easy"),("What is the moral of the story?","Fighting amongst yourselves allows others to take advantage of you.","Easy"),("What does 'frolicking' mean?","Behaving in a playful way.","Easy"),("What does 'neutral' mean?","Not supporting either side in an argument.","Easy"),("What does 'gobbled up' mean?","Ate quickly and greedily.","Easy"),("Were the cats friends before the argument?","Yes, they were friends.","Easy"),("What did the first cat complain about?","That the second cat got the bigger part of the roti.","Easy"),("What did the second cat say in response?","She said it was untrue.","Easy"),("Why did the cats need a judge?","Because they could not agree on whether the pieces were equal.","Easy"),("Where was the monkey when the cats found him?","He was sitting on a wall.","Easy"),("What excuse did the monkey use to take bites?","He said one portion was bigger and needed to be evened out.","Easy"),("How long did it take the monkey to eat the roti?","Within minutes.","Easy"),("What title does Chapter 03 have?","Two Cats and the Monkey.","Easy"),
    ("Why did the monkey readily agree to be the judge?","He saw it as an opportunity to cheat the cats and eat the roti himself.","Medium"),("How did the monkey exploit the cats' trust?","By pretending to equalize portions while actually eating the entire roti bite by bite.","Medium"),("What could the cats have done differently to save their roti?","They could have trusted each other, accepted the slight difference, or measured the pieces themselves.","Medium"),("How does the story illustrate the danger of internal conflict?","The cats' fighting over a small difference gave the monkey the opportunity to exploit them and take everything.","Medium"),("Compare the monkey's cunning with the jackal's foolishness in Chapter 02.","The monkey cleverly exploited others' weakness; the jackal's foolishness only hurt himself.","Medium"),("What lesson does the story teach about trusting strangers?","Strangers may have their own agenda and exploit your vulnerability.","Medium"),("How does the proverb 'United we stand, divided we fall' relate to this story?","The cats divided (fought), so they fell (lost everything to the monkey).","Medium"),("Why were the cats unable to stop the monkey?","They had given him authority as judge and could not challenge his method.","Medium"),("What quality would have saved the cats from losing the roti?","Mutual trust and willingness to compromise.","Medium"),("How can Class 3 students apply this moral in their daily lives?","By resolving disagreements with friends peacefully instead of letting others intervene and take advantage.","Medium"),("Explain the irony in choosing the monkey as a 'neutral' judge.","The monkey was never neutral — he was a self-interested opportunist who exploited their trust.","Medium"),("What does the monkey's vanishing symbolise?","The shamelessness of opportunistic exploitation — he took what he wanted and left without remorse.","Medium"),("How does a small disagreement escalate into total loss in this story?","A tiny size difference → argument → seeking outside judge → monkey exploits → entire roti lost.","Medium"),("What emotional lessons does this story teach children?","Recognising exploitation, controlling anger during disputes, and choosing trustworthy mediators.","Medium"),("How does the story comment on third-party intervention?","Third parties may have hidden agendas; resolving disputes internally is often safer.","Medium"),
    ("Analyse the power dynamics between the cats and the monkey.","The cats voluntarily surrendered decision-making power to the monkey, enabling their own exploitation.","Hard"),("Compare this story with 'The Jackal and the Dhol' in terms of the consequences of poor choices.","Ch02: poor investigation → wasted effort. Ch03: internal fighting → total loss to outsider. Both show poor choices leading to loss.","Hard"),("Evaluate the story as a political allegory.","When citizens fight, corrupt leaders exploit their division for personal gain — mirroring the monkey's exploitation.","Hard"),("Synthesise the progressive wisdom of Chapters 01-03.","Ch01: Think before acting. Ch02: Verify before acting. Ch03: Stay united. Together: Wisdom = Thought + Evidence + Unity.","Hard"),("How does this story develop critical thinking about trust and authority?","It teaches children to evaluate whether those in authority are truly impartial before ceding decision-making power.","Hard"),("Critique the monkey's ethics from a moral perspective.","He represents unchecked opportunistic self-interest without justice, fairness, or conscience.","Hard"),("Formulate the ultimate lesson of Chapter 03 as a life principle.","Unity and trust between friends is more valuable than any material possession; resolve disputes internally.","Hard"),("Design a classroom activity based on this chapter.","Three students role-play cats and monkey; enact the dispute; discuss alternative resolutions afterwards.","Hard"),("Assess how the story builds social-emotional learning.","Teaches conflict resolution, compromise, recognising manipulation, and valuing friendship over material goods.","Hard"),("Write a 4-line poem summarising Chapter 03.","Two cats found a roti, began to fight and shout,\nA clever monkey offered help — but ate it all, no doubt;\nThe cats were left with nothing, their friendship nearly burned,\n'Stay united, don't let outsiders in' — the lesson they both learned!","Hard"),
]
sa_content = f"# Short Answer Questions — Chapter 03: {CH_TITLE}\n\n> **Category**: Short Answer | **Total**: 50 Questions | **Marks**: 2 each\n\n---\n\n"
for idx,(q,a,d) in enumerate(sas,1):
    sa_content += f"### Question {idx}\n- **Question ID**: {CH_ID}_SA_{idx:03d}\n- **Difficulty**: {d}\n- **Marks**: 2\n\n**Question**: {q}\n\n- **Answer Key**: {a}\n\n---\n\n"
with open(os.path.join(CH_DIR, "short_answer.md"), "w", encoding="utf-8") as f: f.write(sa_content)

# ── 5. Long Answer (50) ──
las = [
    ("Narrate the complete story of 'Two Cats and the Monkey' in your own words.","One day, two friendly cats were playing on the road when they found a roti. They decided to share it equally but started arguing about who got the bigger piece. Unable to resolve the dispute, they asked a monkey sitting on a wall to be their judge.\n\nThe cunning monkey had been watching their fight and saw an opportunity. He pretended to compare the pieces, taking a bite from one saying it was bigger, then from the other. He kept repeating this until the entire roti was gone. The helpless cats could only watch. The monkey jumped on the wall and vanished. The cats realised they were foolish to fight and trust a stranger. Moral: Fighting amongst yourselves allows others to take advantage of you.","Easy","Remembering"),
    ("Describe the characters of the two cats and explain their mistake.","The two cats were friends who found a roti and tried to share it equally. However, they were stubborn and distrustful — each thought the other got more. Their mistake was:\n1. Not trusting each other despite being friends.\n2. Fighting over a tiny difference.\n3. Choosing a stranger (monkey) as judge without verifying his intentions.\n4. Ceding all decision-making power to the monkey.","Easy","Understanding"),
    ("Explain the monkey's plan and how he executed it.","The monkey had been observing the cats' fight and saw a chance to eat their roti. His plan:\n1. Eagerly agreed to be 'neutral judge'.\n2. Lifted both pieces and pretended to compare.\n3. Took bites from each piece, always claiming one was bigger.\n4. Repeated this until the entire roti was consumed.\n5. Jumped away and vanished without remorse.","Easy","Understanding"),
    ("Explain the moral of the story with examples.","Moral: Fighting amongst yourselves allows others to take advantage.\nExamples:\n- Two siblings fighting over a toy may have it confiscated by a parent.\n- Two business partners fighting may lose their company to a competitor.\n- Two friends fighting may be manipulated by a third person seeking to benefit.","Easy","Applying"),
    ("Describe the vocabulary words: Frolicking, Neutral, and Gobbled.","1. **Frolicking**: Playing and behaving in a cheerful, lively way. The cats were frolicking on the road.\n2. **Neutral**: Not supporting either side in an argument. The cats wanted a neutral judge.\n3. **Gobbled**: Ate quickly and greedily. The monkey gobbled up the full roti.","Easy","Understanding"),
    ("Why did the cats need a judge and why was their choice poor?","They needed a judge because they could not agree on whether the roti pieces were equal. Their choice was poor because:\n1. The monkey was a stranger with no obligation to be fair.\n2. They did not verify his intentions.\n3. They gave him complete authority without oversight.","Easy","Analyzing"),
    ("What would have happened if the cats had not fought?","If they had not fought, they would have eaten their roti together happily. Even if the pieces were slightly unequal, both would have been satisfied with their share. Fighting cost them everything.","Easy","Applying"),
    ("How does the story show that small problems can become big?","A tiny size difference in the roti pieces was a small problem. But it escalated: argument → tired of arguing → seeking outside help → getting cheated → losing everything. This shows how small disputes can snowball into total loss.","Easy","Analyzing"),
    ("Write a short letter from one cat to the other after the incident.","Dear Friend,\nI am so sorry for our silly fight over the roti. Because of our argument, the cunning monkey ate everything and we got nothing. I have learned that trusting each other is more important than being right about who got the bigger piece. Let us promise to always resolve our differences peacefully from now on.\nYour friend,\nCat","Easy","Creating"),
    ("Summarise Chapter 03 in five key points.","1. Two cats found a roti and decided to share equally.\n2. They argued over who got the bigger piece.\n3. They asked a monkey to judge, who pretended to compare the pieces.\n4. The monkey ate the entire roti by taking bites from each piece.\n5. The cats learned: fighting allows others to take advantage.","Easy","Understanding"),
    ("What role does greed play in both the cats' and monkey's actions?","Cats: Greed made each want the 'bigger' piece instead of accepting what they had.\nMonkey: Greed motivated him to exploit their dispute to eat the entire roti.\nIn both cases, greed led to negative outcomes.","Easy","Analyzing"),
    ("Compare the monkey's cunning with a trickster character from another story.","Like the fox in 'The Fox and the Crow' who flatters the crow to steal the cheese, the monkey exploits the cats' weakness (their dispute) to steal their roti. Both tricksters use others' flaws against them.","Easy","Comparing"),
    ("How did the cats feel at different points in the story?","1. Happy: When they found the roti.\n2. Excited: When they decided to share.\n3. Angry: When they argued over sizes.\n4. Hopeful: When they found a 'neutral' judge.\n5. Helpless: Watching the monkey eat.\n6. Sad and foolish: Realising their mistake.","Easy","Analyzing"),
    ("Why is compromise better than seeking outside judges?","Compromise preserves relationships, ensures both parties get something, and avoids the risk of a biased or self-interested outsider taking everything.","Easy","Evaluating"),
    ("Draft a new ending where the cats solve their problem wisely.","The two cats looked at the slightly unequal pieces. 'Let me take the smaller one,' said the first cat generously. 'No, I will take the smaller one,' replied the second. They laughed and swapped pieces, enjoying their roti together. The monkey on the wall sighed and went looking for food elsewhere.","Easy","Creating"),
    ("Analyse how the monkey maintains control throughout the judging.","He maintains control by: 1) Setting himself as sole authority. 2) Holding both pieces in his hands. 3) Creating a loop of 'this one is bigger' + bite. 4) Moving too quickly for the cats to protest. 5) Continuing until nothing remains.","Medium","Analyzing"),
    ("How does trust between friends break down in this story?","Trust breaks when the cats cannot accept slight inequality. Instead of trusting each other's good intentions, they assume the worst (cheating), which escalates to involving a stranger who exploits them.","Medium","Analyzing"),
    ("Compare the moral of Ch 03 with 'A stitch in time saves nine'.","Both emphasise addressing problems early. If the cats had accepted the tiny difference immediately (stitch in time), they would have saved the entire roti (saves nine).","Medium","Comparing"),
    ("How does this story prepare children for conflict resolution?","It teaches: 1) Stay calm during disagreements. 2) Compromise is better than winning at all costs. 3) Be careful who you trust to mediate. 4) Internal resolution is safer than external intervention.","Medium","Applying"),
    ("Explain the concept of 'opportunity exploitation' using the monkey's actions.","The monkey saw the cats' internal conflict as an opportunity. He positioned himself as a helper but used his authority to exploit them for personal gain — a classic case of opportunity exploitation.","Medium","Analyzing"),
    ("How does the story illustrate the consequence of stubbornness?","Both cats stubbornly insisted the other got more. Neither would compromise. This stubbornness led them to seek external help, which resulted in total loss. Stubbornness caused them to lose what flexibility would have preserved.","Medium","Evaluating"),
    ("What makes the monkey a successful manipulator?","1) He observed the vulnerability first. 2) He offered help eagerly. 3) He created a plausible excuse (making portions equal). 4) He acted quickly. 5) He left before they could react. This is a textbook manipulation pattern.","Medium","Analyzing"),
    ("How would you advise the cats if you were their friend?","I would say: 'Friends, a small difference in size does not matter when you both get to eat. Accept the pieces as they are, enjoy your meal together, and never let a small issue destroy your friendship.'","Medium","Applying"),
    ("Discuss the theme of 'Appearances vs Reality' in the story.","Appearance: The monkey appears neutral and helpful.\nReality: He is a selfish opportunist.\nAppearance: The pieces seem unequal.\nReality: The difference was negligible.\nBoth appearances deceived the cats.","Medium","Analyzing"),
    ("How does the narrative structure create suspense?","The story builds suspense by: 1) Setting up the roti find (hope). 2) The argument (tension). 3) Finding the monkey (relief). 4) The monkey eating bite by bite (growing horror). 5) Complete loss (shock). This arc keeps readers engaged.","Medium","Analyzing"),
    ("Why is the story's setting (street, wall) significant?","The street is a public place where disputes happen openly. The wall gives the monkey a vantage point to observe — and a quick escape route. These settings enable the plot naturally.","Medium","Analyzing"),
    ("How does the Panchatantra make moral lessons memorable?","Through: 1) Relatable animal characters. 2) Clear conflict and resolution. 3) Dramatic consequences. 4) Explicit moral statement. 5) Simple language for all ages.","Medium","Evaluating"),
    ("What are the consequences of not resolving conflicts peacefully?","Loss of resources (roti), damaged relationships (friendship), exploitation by outsiders (monkey), and emotional regret (foolishness). This story demonstrates all four.","Medium","Evaluating"),
    ("Design a classroom poster based on the moral of Chapter 03.","Title: 'United We Share, Divided We Lose'\nImage: Two cats smiling while sharing roti vs. a monkey eating between fighting cats.\nMessage: 'Resolve disputes together — don't let outsiders take what belongs to you!'","Medium","Creating"),
    ("Explain how this story connects to the concept of teamwork.","Teamwork requires trust, communication, and compromise. The cats failed at all three: they didn't trust each other, communicated through arguments, and refused to compromise. Result: they lost everything.","Medium","Evaluating"),
    ("Evaluate the philosophical significance of the moral for human societies.","When groups — families, communities, nations — fight internally, external powers exploit the division. History proves this repeatedly: colonialism thrived on divided societies. The Panchatantra recognised this truth millennia ago.","Hard","Evaluating"),
    ("Analyse the story through the lens of game theory.","In game theory, the cats face a cooperation vs. competition dilemma. Cooperation (sharing) yields a moderate reward for both. Competition (fighting) yields zero for both and maximum for the monkey (defector). The cats chose competition and lost.","Hard","Analyzing"),
    ("Compare the monkey's role to that of corrupt intermediaries in society.","Corrupt intermediaries (lawyers, middlemen, corrupt officials) exploit disputes between parties for personal gain — exactly as the monkey exploited the cats' fight. Both profit from others' conflicts.","Hard","Evaluating"),
    ("Synthesise how Chapters 01-03 create a complete decision-making framework.","Ch01: Think before acting (foresight).\nCh02: Gather information before acting (evidence).\nCh03: Resolve disputes internally (unity).\nTogether: Wisdom = Foresight + Evidence + Unity — a comprehensive framework for young learners.","Hard","Synthesizing"),
    ("Critique the narrative from a feminist perspective.","While the cats' gender is unspecified in the original, the story universally teaches conflict resolution regardless of gender. The moral about exploitation through division is applicable to all.","Hard","Evaluating"),
    ("Design a debate topic for Class 3 students based on this chapter.","Topic: 'Should you always solve problems with friends by yourselves, or is it okay to ask someone else to help?'\nTeam A: Internal resolution preserves trust.\nTeam B: Sometimes external mediators bring fairness.\nDebrief: Discuss when each approach works best.","Hard","Creating"),
    ("Assess the story's effectiveness in teaching emotional regulation.","Highly effective: It shows that uncontrolled anger (fighting over roti) leads to exploitation. Emotional regulation (staying calm, compromising) would have preserved both the roti and the friendship.","Hard","Evaluating"),
    ("How does the story model consequential thinking for children?","It shows: Action (fighting) → Consequence (seeking judge) → Further Consequence (exploitation) → Final Consequence (total loss). Children learn to trace action-consequence chains.","Hard","Analyzing"),
    ("Formulate a comprehensive moral lesson combining all three chapters.","Think carefully (Ch01), investigate thoroughly (Ch02), and stand united (Ch03). Never let impulsiveness, ignorance, or internal conflict create opportunities for others to exploit you.","Hard","Creating"),
    ("Write a book review of Chapter 03 for a school magazine.","'Two Cats and the Monkey' is a brilliantly crafted Panchatantra tale about two cats who lose their entire roti to a cunning monkey because of a petty argument. With vivid characters and a powerful moral about unity, it teaches young readers that fighting amongst friends only benefits outsiders. A timeless lesson in every bite — literally!","Hard","Creating"),
]
la_content = f"# Long Answer Questions — Chapter 03: {CH_TITLE}\n\n> **Category**: Long Answer | **Total**: 50 Questions | **Marks**: 5 each\n\n---\n\n"
for idx,(q,a,d,bl) in enumerate(las,1):
    la_content += f"### Question {idx}\n- **Question ID**: {CH_ID}_LA_{idx:03d}\n- **Difficulty**: {d}\n- **Bloom Level**: {bl}\n- **Marks**: 5\n\n**Question**: {q}\n\n- **Answer Key**: {a}\n\n---\n\n"
with open(os.path.join(CH_DIR, "long_answer.md"), "w", encoding="utf-8") as f: f.write(la_content)

# ── 6. Extract Based (50 = 10 sets × 5) ──
exts = [
    ("One day, two cats were frolicking on the road. There, they found a roti lying on the street.",[("What were the cats doing on the road?","Frolicking (playing).","Easy"),("What did they find?","A roti lying on the street.","Easy"),("What does 'frolicking' mean?","Behaving in a playful way.","Easy"),("Were the cats strangers or friends?","They were friends.","Easy"),("Where was the roti lying?","On the street.","Medium")]),
    ("The cats were friends so they decided to share the roti equally between themselves. They tore the roti into two.",[("How did the cats plan to divide the roti?","Equally between themselves.","Easy"),("What did they do to the roti?","They tore it into two pieces.","Easy"),("Were the cats cooperative at first?","Yes, they decided to share.","Easy"),("What quality did they show initially?","Friendship and willingness to share.","Medium"),("What went wrong after tearing the roti?","They argued about who got the bigger piece.","Medium")]),
    ("But they soon got into an argument. The first one complained that the second cat had got the bigger part which was unfair.",[("Why did the cats argue?","Each thought the other got the bigger part.","Easy"),("Who complained first?","The first cat.","Easy"),("Was the complaint about being fair or unfair?","Unfair — the bigger part was unfair.","Easy"),("Did the second cat agree with the complaint?","No, she said it was untrue.","Medium"),("How did this argument escalate?","It went on until they became tired and sought a judge.","Medium")]),
    ("Finally the cats became tired of arguing and decided to find a neutral judge for this problem.",[("Why did the cats seek a judge?","They were tired of arguing and could not resolve it.","Easy"),("What kind of judge did they want?","A neutral judge.","Easy"),("What does 'neutral' mean?","Not supporting either side.","Easy"),("Was seeking an outside judge a wise decision?","No, it led to exploitation by the monkey.","Medium"),("What should they have done instead?","Compromised and accepted the slight difference.","Medium")]),
    ("They looked around and found a monkey sitting on a wall and approached him with their problem.",[("Where was the monkey sitting?","On a wall.","Easy"),("Did the cats know the monkey personally?","No, he was a stranger.","Easy"),("Why did they choose the monkey?","He was nearby and seemed available.","Easy"),("Was the monkey trustworthy?","No, he had selfish intentions.","Medium"),("What is the danger of choosing convenience over trustworthiness?","Convenient choices may not be reliable or fair.","Hard")]),
    ("The monkey had been sitting there for quite some time and had observed their fight. He was looking for an opportunity to grab the roti for himself.",[("Had the monkey seen the fight?","Yes, he observed it for some time.","Easy"),("What was the monkey's real intention?","To grab the roti for himself.","Easy"),("Did the monkey reveal his true intentions?","No, he pretended to be a fair judge.","Medium"),("What does this tell us about the monkey's character?","He was cunning, selfish, and deceptive.","Medium"),("How does this show opportunistic behaviour?","He waited for the right moment to exploit the cats' weakness.","Hard")]),
    ("He pretended to compare them and took a bite from one portion. 'This portion was bigger', he said.",[("What did the monkey pretend to do?","Compare the two portions.","Easy"),("What did he actually do?","Took a bite from one portion.","Easy"),("What excuse did he give?","'This portion was bigger.'","Easy"),("Was his comparison genuine?","No, it was a trick to eat the roti.","Medium"),("How did he maintain the deception?","By repeating the 'bigger' claim and taking bites from both sides.","Hard")]),
    ("He kept on doing this and the foolish cats could only look at him helplessly. Within minutes, the monkey gobbled up the full roti.",[("How did the cats feel while watching?","Helpless.","Easy"),("How long did it take the monkey to finish?","Within minutes.","Easy"),("Why are the cats called 'foolish'?","Because they trusted a stranger and lost everything.","Medium"),("What does 'gobbled up' mean?","Ate quickly and greedily.","Easy"),("What does the cats' helplessness show about ceded authority?","Once authority is given away, it is hard to take it back.","Hard")]),
    ("The cats did not get even a single bite for themselves. They realised that they were foolish to fight amongst themselves and trust a stranger.",[("Did the cats get any roti?","No, not even a single bite.","Easy"),("What two mistakes did they realise?","Fighting amongst themselves and trusting a stranger.","Easy"),("What emotion did they feel at the end?","Regret and foolishness.","Medium"),("What lesson did they learn?","Don't fight internally or trust strangers with your disputes.","Medium"),("How can this lesson apply to students' lives?","By resolving disagreements with friends peacefully without involving untrustworthy people.","Hard")]),
    ("Moral of the Story: Fighting amongst yourselves allows others to take advantage of you.",[("What is the moral of the story?","Fighting amongst yourselves allows others to take advantage.","Easy"),("Who took advantage in this story?","The monkey.","Easy"),("How did fighting allow the monkey to take advantage?","Their dispute gave him the opportunity to eat everything.","Medium"),("Give a real-life example of this moral.","Siblings fighting over a toy may have it confiscated by a parent.","Medium"),("How does this moral relate to the concept of unity?","Unity prevents exploitation; division invites it.","Hard")]),
]
ext_content = f"# Extract Based Questions — Chapter 03: {CH_TITLE}\n\n> **Category**: Extract Based | **Total**: 10 Extract Sets (50 Questions) | **Marks**: 1 each\n\n---\n\n"
qc = 1
for si,(ex,qs) in enumerate(exts,1):
    ext_content += f"## Extract Set {si}\n\n> *\"{ex}\"*\n\n---\n"
    for q,a,d in qs:
        ext_content += f"\n### Question {qc}\n- **Question ID**: {CH_ID}_EXT_{qc:03d}\n- **Difficulty**: {d}\n- **Marks**: 1\n\n**Question**: {q}\n\n- **Answer Key**: {a}\n"
        qc += 1
    ext_content += "\n\n---\n\n"
with open(os.path.join(CH_DIR, "extract_based.md"), "w", encoding="utf-8") as f: f.write(ext_content)

print(f"SUCCESS: Generated all 6 category files (300 Qs) for Chapter 03 in {CH_DIR}")
